-- Nusantara Star — curated supply-interest inbox V1
-- One submission may create at most one private onboarding profile. Link tokens are generated by the server and never stored.
alter table public.supply_interest_submissions
  add column if not exists onboarding_talent_id uuid references public.talents(id) on delete set null,
  add column if not exists invited_at timestamptz null;

create unique index if not exists supply_interest_submissions_one_onboarding_profile_idx
  on public.supply_interest_submissions (onboarding_talent_id)
  where onboarding_talent_id is not null;

create or replace function public.ns_create_supply_interest_invite_v1(
  p_interest_id uuid,
  p_talent_category text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  interest_row public.supply_interest_submissions%rowtype;
  profile_id uuid;
  category_value text := trim(coalesce(p_talent_category, ''));
  valid_talent_categories text[] := array['Solo', 'Duo/Trio', 'Band', 'DJ', 'MC/Host', 'Speaker', 'Traditional/Ethnic', 'Specialty Performer'];
begin
  select * into interest_row
  from public.supply_interest_submissions
  where id = p_interest_id
  for update;

  if not found then raise exception 'Pendaftaran minat tidak ditemukan'; end if;
  if interest_row.status = 'archived' then raise exception 'Pendaftaran yang diarsipkan tidak dapat diundang'; end if;

  if interest_row.onboarding_talent_id is not null then
    return jsonb_build_object(
      'talent_id', interest_row.onboarding_talent_id,
      'email', interest_row.email,
      'supply_type', interest_row.supply_type,
      'created', false
    );
  end if;

  if interest_row.status <> 'new' then raise exception 'Pendaftaran tidak dapat diproses'; end if;
  if interest_row.supply_type = 'talent' and not (category_value = any(valid_talent_categories)) then
    raise exception 'Kategori Talent tidak valid';
  end if;

  profile_id := gen_random_uuid();
  insert into public.talents (id, name, category, supply_type, status, onboarding_status, public_visible)
  values (
    profile_id,
    '',
    case when interest_row.supply_type = 'talent' then category_value else '' end,
    interest_row.supply_type,
    'draft',
    'not_started',
    false
  );

  update public.supply_interest_submissions
  set status = 'invited', onboarding_talent_id = profile_id, invited_at = now()
  where id = interest_row.id;

  return jsonb_build_object(
    'talent_id', profile_id,
    'email', interest_row.email,
    'supply_type', interest_row.supply_type,
    'created', true
  );
end;
$$;

revoke all on function public.ns_create_supply_interest_invite_v1(uuid, text) from public, anon, authenticated;
grant execute on function public.ns_create_supply_interest_invite_v1(uuid, text) to service_role;

comment on function public.ns_create_supply_interest_invite_v1(uuid, text) is 'Atomically converts a reviewed supply-interest submission into one private onboarding profile; never publishes supply.';
