"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { bookingStatusLabel } from "@/lib/ui-language";

type Booking={id:string;status:string;event_date:string;buyer_price:number|null;buyer_terms_accepted_at?:string|null;financial_security_status?:string;financial_security_reference?:string|null}|null;
type Payment={id:string;payment_type:string|null;amount:number;status:string;paid_at:string|null};
const money=(value:number|null)=>value==null?"—":new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);

export function AdminBookingActions({briefId,talentName,booking,payments}:{briefId:string;talentName:string;booking:Booking;payments:Payment[]}){
 const router=useRouter();const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[securityType,setSecurityType]=useState("approved_po_credit");const[reference,setReference]=useState("");const[termsAccepted,setTermsAccepted]=useState(Boolean(booking?.buyer_terms_accepted_at));
 async function bookingAction(action:string,extra:Record<string,string>={}){setBusy(action);setError(null);try{const r=await fetch("/api/internal-demo/admin/booking",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({briefId,action,...extra})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Aksi booking gagal");if(action==="accept_buyer_terms")setTermsAccepted(true);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Aksi booking gagal")}finally{setBusy(null)}}
 async function paymentAction(action:string,paymentId?:string){if(!booking)return;setBusy(action);setError(null);try{const r=await fetch("/api/internal-demo/admin/payment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId:booking.id,action,paymentId})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Aksi pembayaran gagal");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Aksi pembayaran gagal")}finally{setBusy(null)}}
 const paidTotal=payments.filter(p=>p.status==="paid").reduce((sum,p)=>sum+Number(p.amount??0),0);const pendingPayment=payments.find(p=>p.status==="pending");
 return <section className="mt-7 border border-black/10 bg-white p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">Booking Terjamin</p><p className="mt-1 text-xs text-black/45">Talent: {talentName}. Talent dipilih belum berarti booking final.</p></div>{booking?<span className="border border-black/15 px-3 py-2 text-xs font-semibold uppercase">{bookingStatusLabel(booking.status)}</span>:null}</div>
 {!booking?<div className="mt-5"><p className="text-sm text-black/60">Buat booking dengan status menunggu jaminan pembayaran. Belum terjamin.</p><button onClick={()=>bookingAction("create_booking")} disabled={busy!==null} className="mt-3 bg-black px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy?"Memproses…":"Buat booking menunggu jaminan"}</button></div>:<><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="border border-black/10 p-3 text-sm"><span className="text-black/45">Harga ke klien</span><br/>{money(booking.buyer_price)}</div><div className="border border-black/10 p-3 text-sm"><span className="text-black/45">Ketentuan klien</span><br/>{termsAccepted?"Disetujui":"Belum disetujui"}</div><div className="border border-black/10 p-3 text-sm"><span className="text-black/45">Jaminan pembayaran</span><br/>{booking.financial_security_status??(booking.status==="secured"?"Terpenuhi":"Menunggu")}</div><div className="border border-black/10 p-3 text-sm"><span className="text-black/45">Pembayaran klien</span><br/>{money(paidTotal)}</div></div>
 {booking.status==="pending_security"&&!termsAccepted?<button onClick={()=>bookingAction("accept_buyer_terms")} disabled={busy!==null} className="mt-4 border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Catat ketentuan klien disetujui</button>:null}
 {booking.status==="pending_security"?<div className="mt-5 border-t border-black/10 pt-5"><p className="text-sm font-semibold">Jaminan Pembayaran</p><p className="mt-1 text-xs text-black/45">Tidak ada DP universal. Pembayaran mengikuti tahapan kesepakatan yang sudah dikunci.</p>{!pendingPayment?<button onClick={()=>paymentAction("create_next_buyer_payment")} disabled={busy!==null} className="mt-3 border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Buat tahapan pembayaran berikutnya</button>:null}{pendingPayment?<div className="mt-3 border border-black/10 p-4 text-sm">Menunggu: {pendingPayment.payment_type} · {money(pendingPayment.amount)}<br/><button onClick={()=>paymentAction("mark_paid",pendingPayment.id)} disabled={busy!==null} className="mt-3 bg-black px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Tandai sudah dibayar</button></div>:null}<div className="mt-4 grid gap-2 md:grid-cols-[220px_1fr_auto]"><select value={securityType} onChange={e=>setSecurityType(e.target.value)} className="border border-black/15 p-2 text-sm"><option value="approved_po_credit">PO/Kredit disetujui</option><option value="authorized_exception">Pengecualian berwenang</option></select><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Referensi PO / catatan pengecualian" className="border border-black/15 p-2 text-sm"/><button onClick={()=>bookingAction("set_security",{securityType,reference})} disabled={busy!==null} className="border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Simpan jaminan</button></div><button onClick={()=>bookingAction("secure_booking")} disabled={busy!==null} className="mt-5 bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Evaluasi & amankan booking</button></div>:null}{booking.status==="secured"?<p className="mt-5 bg-black p-4 text-sm font-semibold text-white">✓ BOOKING TERJAMIN</p>:null}</>}{error?<p className="mt-3 text-xs font-semibold text-red-700">{error}</p>:null}</section>;
}
