"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import type { OperationsChecklistItem, OperationsIncident, TalentSettlement } from "@/lib/operations-data";
import { bookingStatusLabel } from "@/lib/ui-language";

type Booking={id:string;status:string;event_date:string;talent_payable:number|null;pre_show_at?:string|null;completed_at?:string|null};
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
const incidentOptions=[["buyer_cancellation","Pembatalan oleh klien"],["talent_cancellation","Pembatalan oleh talent"],["postponement","Penundaan"],["no_show","Tidak hadir"],["late_arrival","Terlambat hadir"],["shortened_performance","Durasi tampil dipersingkat"],["technical_failure","Kendala teknis"],["payment_dispute","Sengketa pembayaran"],["force_majeure","Keadaan kahar"],["other","Lainnya"]] as const;
const incidentLabel=(v:string)=>incidentOptions.find(([x])=>x===v)?.[1]??v;

export function AdminOperations({booking,checklist,incidents,settlements}:{booking:Booking;checklist:OperationsChecklistItem[];incidents:OperationsIncident[];settlements:TalentSettlement[]}){
 const router=useRouter();const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[incidentType,setIncidentType]=useState("technical_failure");const[incidentSummary,setIncidentSummary]=useState("");const[settlementAmount,setSettlementAmount]=useState("");const[settlementProvider,setSettlementProvider]=useState("");const[settlementReference,setSettlementReference]=useState("");
 const paid=useMemo(()=>settlements.filter(r=>r.status==="paid").reduce((s,r)=>s+Number(r.amount??0),0),[settlements]);const remaining=Math.max(0,Number(booking.talent_payable??0)-paid);const openIncidents=incidents.filter(r=>r.status==="open");
 async function act(action:string,extra:Record<string,unknown>={}){setBusy(action);setError(null);try{const r=await fetch("/api/internal-demo/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId:booking.id,action,...extra})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Aksi operasional gagal");if(action==="report_incident")setIncidentSummary("");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Aksi operasional gagal")}finally{setBusy(null)}}
 async function recordSettlement(){const amount=Number(settlementAmount);if(!Number.isSafeInteger(amount)||amount<=0){setError("Nominal pembayaran tidak valid");return}if(!settlementReference.trim()){setError("Bukti atau referensi pembayaran wajib diisi");return}setBusy("settlement");setError(null);try{const key=`${booking.id}:${settlementReference.trim()}:${amount}`;const r=await fetch("/api/internal-demo/admin/settlement",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bookingId:booking.id,amount,provider:settlementProvider,providerReference:settlementReference,idempotencyKey:key})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Pencatatan pembayaran gagal");setSettlementAmount("");setSettlementProvider("");setSettlementReference("");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Pencatatan pembayaran gagal")}finally{setBusy(null)}}
 return <section className="mt-7 border border-black/10 bg-white p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">Operasional</p><p className="mt-1 text-xs text-black/45">Pra-acara → tampil → selesai/insiden → penyelesaian pembayaran</p></div><span className="border border-black/15 px-3 py-2 text-xs font-semibold uppercase">{bookingStatusLabel(booking.status)}</span></div>
 {booking.status==="secured"?<button onClick={()=>act("initialize_pre_show")} disabled={busy!==null} className="mt-5 bg-black px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Mulai checklist pra-acara</button>:null}
 {checklist.length>0?<div className="mt-6"><p className="text-sm font-semibold">Checklist Pra-acara</p><div className="mt-3 divide-y divide-black/10 border border-black/10">{checklist.map(item=><div key={item.id} className="flex flex-col gap-3 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium">{item.checkpoint_code} · {item.label}</p><p className="mt-1 text-xs text-black/45">Batas waktu {item.due_date}</p></div><select value={item.status} disabled={busy!==null||booking.status==="completed"} onChange={e=>act("set_checklist_status",{itemId:item.id,status:e.target.value})} className="border border-black/15 p-2 text-xs"><option value="pending">Menunggu</option><option value="done">Selesai</option><option value="not_applicable">Tidak berlaku</option></select></div>)}</div></div>:null}
 {!['completed','cancelled'].includes(booking.status)?<div className="mt-6 border-t border-black/10 pt-5"><p className="text-sm font-semibold">Insiden</p><div className="mt-3 grid gap-2 md:grid-cols-[220px_1fr_auto]"><select value={incidentType} onChange={e=>setIncidentType(e.target.value)} className="border border-black/15 p-2 text-sm">{incidentOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input value={incidentSummary} onChange={e=>setIncidentSummary(e.target.value)} placeholder="Ringkasan kejadian" className="border border-black/15 p-2 text-sm"/><button onClick={()=>act("report_incident",{incidentType,summary:incidentSummary})} disabled={busy!==null||!incidentSummary.trim()} className="border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Catat insiden</button></div></div>:null}
 {incidents.length>0?<div className="mt-4 space-y-2">{incidents.map(i=><div key={i.id} className="border border-black/10 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{incidentLabel(i.incident_type)}</strong><span className="text-xs uppercase">{i.status==="open"?"Terbuka":"Selesai"}</span></div><p className="mt-1 text-black/65">{i.summary}</p>{i.status==="open"?<button onClick={()=>act("resolve_incident",{incidentId:i.id})} disabled={busy!==null} className="mt-3 border border-black px-3 py-2 text-xs font-semibold disabled:opacity-40">Selesaikan insiden</button>:null}</div>)}</div>:null}
 {["secured","pre_show"].includes(booking.status)&&openIncidents.length===0?<button onClick={()=>act("complete_show")} disabled={busy!==null} className="mt-6 bg-black px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Tandai pertunjukan selesai</button>:null}
 <div className="mt-6 border-t border-black/10 pt-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-sm font-semibold">Penyelesaian Pembayaran Talent</p><p className="mt-1 text-xs text-black/45">Mencatat pembayaran aktual; kewajiban terencana tetap mengikuti jadwal pembayaran.</p></div><div className="text-right text-xs text-black/55">Dibayar {money(paid)} · Sisa {money(remaining)}</div></div>{["secured","pre_show","completed"].includes(booking.status)&&remaining>0?<div className="mt-3 grid gap-2 md:grid-cols-4"><input type="number" min="1" step="1" value={settlementAmount} onChange={e=>setSettlementAmount(e.target.value)} placeholder="Nominal" className="border border-black/15 p-2 text-sm"/><input value={settlementProvider} onChange={e=>setSettlementProvider(e.target.value)} placeholder="Bank/penyedia" className="border border-black/15 p-2 text-sm"/><input value={settlementReference} onChange={e=>setSettlementReference(e.target.value)} placeholder="Bukti/referensi transfer" className="border border-black/15 p-2 text-sm"/><button onClick={recordSettlement} disabled={busy!==null} className="border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Catat dibayar</button></div>:null}{settlements.length>0?<div className="mt-3 space-y-2">{settlements.map(r=><div key={r.id} className="border border-black/10 p-3 text-sm">{money(r.amount)} · {r.provider??"—"} · {r.provider_reference} · <strong>{r.status==="paid"?"Dibayar":r.status}</strong></div>)}</div>:null}</div>{error?<p className="mt-4 text-xs font-semibold text-red-700">{error}</p>:null}</section>;
}
