"use client";
import { useState } from "react";
import { CheckCircle2, Send } from "lucide-react";
import type { Locale } from "@/lib/i18n";

type C = { eyebrow: string; title: string; body: string; contact: string; event: string; talent: string; submit: string; note: string; success: string };
const Field = ({ label, name, type="text", required=false, options, area=false }: { label: string; name: string; type?: string; required?: boolean; options?: string[]; area?: boolean }) => <label className={area ? "md:col-span-2" : ""}><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.17em] text-black/55">{label}{required && " *"}</span>{area ? <textarea name={name} rows={5} className="w-full border border-black/25 bg-transparent p-4 outline-none focus:border-ember"/> : options ? <select required={required} name={name} defaultValue="" className="h-13 w-full border border-black/25 bg-paper px-4 py-3 outline-none focus:border-ember"><option value="" disabled>—</option>{options.map(x => <option key={x}>{x}</option>)}</select> : <input required={required} type={type} name={name} className="h-13 w-full border border-black/25 bg-transparent px-4 py-3 outline-none focus:border-ember"/>}</label>;
export function BriefForm({ locale, copy: t }: { locale: Locale; copy: C }) {
  const [sent, setSent] = useState(false); const id = locale === "id";
  return <section className="px-5 py-16 md:px-10 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-14 lg:grid-cols-[.75fr_1.25fr]"><div className="lg:sticky lg:top-32 lg:self-start"><p className="eyebrow">{t.eyebrow}</p><h1 className="mt-5 font-display text-5xl leading-none md:text-7xl">{t.title}</h1><p className="mt-7 max-w-md leading-7 text-black/55">{t.body}</p><div className="mt-10 border-l-2 border-ember pl-5 text-sm leading-6 text-black/55">{t.note}</div></div>{sent ? <div className="flex min-h-[500px] flex-col items-center justify-center border border-black/15 bg-white p-10 text-center"><CheckCircle2 size={48} className="text-ember"/><h2 className="mt-6 font-display text-4xl">{t.success}</h2></div> : <form onSubmit={e => {e.preventDefault(); setSent(true); window.scrollTo({top:0,behavior:"smooth"});}} className="space-y-14 bg-white p-6 shadow-[0_20px_70px_rgba(0,0,0,.06)] md:p-12"><fieldset><legend className="mb-7 font-display text-3xl">01. {t.contact}</legend><div className="grid gap-6 md:grid-cols-2"><Field label={id?"Nama":"Name"} name="name" required/><Field label={id?"Perusahaan":"Company"} name="company"/><Field label="WhatsApp" name="whatsapp" required/><Field label="Email" name="email" type="email" required/></div></fieldset><fieldset><legend className="mb-7 font-display text-3xl">02. {t.event}</legend><div className="grid gap-6 md:grid-cols-2"><Field label={id?"Jenis acara":"Event type"} name="eventType" required options={["Corporate event","Brand activation","Wedding","Festival","Private event","Other"]}/><Field label={id?"Tanggal acara":"Event date"} name="date" type="date" required/><Field label={id?"Kota":"City"} name="city" required/><Field label="Venue" name="venue"/><Field label={id?"Jumlah audiens":"Audience size"} name="audience" type="number"/></div></fieldset><fieldset><legend className="mb-7 font-display text-3xl">03. {t.talent}</legend><div className="grid gap-6 md:grid-cols-2"><Field label={id?"Kategori talent":"Talent category"} name="category" required options={["Singer","Band","MC / Host","DJ","Traditional arts","Speaker"]}/><Field label="Genre / style" name="genre"/><Field label="Budget" name="budget" required options={["< Rp10 jt","Rp10–25 jt","Rp25–50 jt","Rp50–100 jt","Rp100 jt+"]}/><Field label={id?"Durasi tampil":"Performance duration"} name="duration" options={["15–30 minutes","30–60 minutes","60–90 minutes","90+ minutes"]}/><Field label={id?"Catatan tambahan":"Additional notes"} name="notes" area/></div></fieldset><button className="flex h-14 w-full items-center justify-center gap-3 bg-ink text-xs font-bold uppercase tracking-[.15em] text-white transition hover:bg-ember">{t.submit}<Send size={16}/></button></form>}</div></section>;
}
