"use client";
import { useEffect,useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";
type Q={key:string;question:string;required:boolean};type R={id:string;version_no:number;source_type:string;source_filename?:string|null;normalized_data?:Record<string,unknown>;missing_questions?:Q[];answers?:Record<string,string>;normalization_source?:string;status:string};
const labels:Record<string,string>={party_size:"Total personel",performers_count:"Performer",crew_count:"Crew",departure_city:"Kota keberangkatan",technical_requirements:"Kebutuhan technical",stage_backline:"Stage / backline",hospitality:"Hospitality",transport_requirements:"Transport",baggage_requirements:"Baggage alat",accommodation_required:"Butuh akomodasi",accommodation_requirements:"Akomodasi",meals_per_diem:"Meal / per diem",special_requirements:"Kebutuhan khusus",notes:"Catatan"};
const statusText=(s:string)=>({needs_talent_input:"Perlu dilengkapi",ready_for_admin:"Siap direview admin",admin_approved:"Disetujui admin",superseded:"Tidak aktif"}[s]??s);
function hasValue(v:unknown){return Array.isArray(v)?v.length>0:v!==null&&v!==undefined&&v!==""}
export function RiderMaintenance({talentId,talentName,token}:{talentId:string;talentName:string;token:string}){const[rider,setRider]=useState<R|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");async function refresh(){const r=await fetch(`/api/talent-onboarding/rider-status?talentId=${encodeURIComponent(talentId)}&token=${encodeURIComponent(token)}`,{cache:"no-store"});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail??b?.error??"Gagal memuat rider");setRider(b?.rider??null);setAnswers(b?.rider?.answers??{})}useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
async function upload(file:File|null){if(!file)return;setBusy(true);setError("");setMessage("");try{const prep=await fetch("/api/talent-onboarding/rider",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,fileName:file.name,mimeType:file.type,sizeBytes:file.size})});const p=await prep.json().catch(()=>null);if(!prep.ok)throw new Error(p?.detail??p?.error??"Upload rider gagal");const s=getSupabaseBrowserClient();if(!s)throw new Error("Supabase browser client belum dikonfigurasi");const{error:ue}=await s.storage.from("talent-documents").uploadToSignedUrl(p.path,p.token,file,{contentType:file.type});if(ue)throw ue;const verify=await fetch("/api/talent-onboarding/rider",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,assetId:p.assetId})});const result=await verify.json().catch(()=>null);if(!verify.ok)throw new Error(result?.error??result?.detail??"Rider belum dapat diproses");setMessage("Draft rider berhasil dibuat. Lengkapi hanya informasi yang memang belum ada.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Upload rider gagal")}finally{setBusy(false)}}
async function save(){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/talent-onboarding/rider-status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,answers})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail??b?.error??"Gagal menyimpan");setMessage(b?.rider?.status==="ready_for_admin"?"Rider lengkap dan siap direview admin.":"Jawaban tersimpan. Masih ada informasi yang perlu dilengkapi.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan")}finally{setBusy(false)}}
async function discard(){if(!rider)return;setBusy(true);setError("");try{const r=await fetch("/api/talent-onboarding/rider-status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,action:"discard_current"})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.detail??b?.error??"Gagal membatalkan draft");setMessage("Draft rider dibatalkan. Silakan upload rider yang benar.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Gagal membatalkan draft")}finally{setBusy(false)}}
const questions=Array.isArray(rider?.missing_questions)?rider!.missing_questions!:[],entries=Object.entries(rider?.normalized_data??{}).filter(([,v])=>hasValue(v));const legacy=rider?.normalization_source==="rules";
return <main className="min-h-screen bg-[#f5f3ee] px-5 py-10 text-[#171713] md:px-10"><div className="mx-auto max-w-3xl"><p className="eyebrow">Nusantara Star · Rider</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.03em]">Master rider · {talentName}</h1><p className="mt-3 text-sm text-black/55">Upload rider terbaru. Sistem membaca dokumen, menstandarkan isinya, lalu menanyakan hanya data dasar yang belum jelas.</p>
<section className="mt-8 border border-black/10 bg-white p-5 md:p-6"><p className="text-sm font-semibold">Upload rider terbaru</p><p className="mt-1 text-xs text-black/50">PDF/DOCX/TXT maks. 15 MB. File asli tetap menjadi sumber utama.</p><input type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" disabled={busy} onChange={e=>upload(e.target.files?.[0]??null)} className="mt-4 block w-full text-sm"/></section>
<section className="mt-5 border border-black/10 bg-white p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">{rider?.status==="admin_approved"?"Master rider aktif":"Draft rider terbaru"}</p><span className="border border-black/10 px-3 py-2 text-xs font-semibold">{rider?`V${rider.version_no} · ${statusText(rider.status)}`:"Belum ada"}</span></div>{rider?<><p className="mt-3 text-xs text-black/50">Sumber: {rider.source_filename||rider.source_type}</p>{legacy?<div className="mt-4 border border-red-300 bg-red-50 p-4 text-sm text-red-800"><strong>Draft lama tidak valid.</strong> Normalisasi sebelumnya gagal dan tidak boleh dipakai.</div>:entries.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{entries.map(([k,v])=><div key={k} className="border border-black/10 p-4"><p className="text-xs font-semibold text-black/50">{labels[k]??k}</p><p className="mt-1 text-sm">{Array.isArray(v)?v.join("; "):typeof v==="boolean"?(v?"Ya":"Tidak"):String(v)}</p></div>)}</div>:<p className="mt-4 text-sm text-black/50">Belum ada data rider yang berhasil dinormalisasi.</p>}{rider.status!=="admin_approved"?<button disabled={busy} onClick={discard} className="mt-4 border border-red-700 px-4 py-2 text-sm font-semibold text-red-700 disabled:opacity-40">Batalkan draft ini</button>:null}</>:<p className="mt-4 text-sm text-black/50">Belum ada master rider. Upload rider untuk membuat draft pertama.</p>}</section>
{questions.length&&!legacy?<section className="mt-5 border border-black/10 bg-white p-5 md:p-6"><p className="text-sm font-semibold">Lengkapi yang masih kurang</p><p className="mt-1 text-xs text-black/50">Jawab hanya berdasarkan fakta operasional talent.</p><div className="mt-4 space-y-4">{questions.map(q=><label key={q.key} className="block text-sm font-semibold">{q.question}<input value={answers[q.key]??""} onChange={e=>setAnswers(v=>({...v,[q.key]:e.target.value}))} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal"/></label>)}</div><button disabled={busy} onClick={save} className="mt-5 border border-black bg-black px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Simpan & cek ulang</button></section>:rider?.status==="ready_for_admin"?<div className="mt-5 border border-green-700/20 bg-green-50 p-4 text-sm font-semibold text-green-800">✓ Rider siap direview admin.</div>:null}
{message?<p className="mt-4 text-sm font-semibold text-green-700">{message}</p>:null}{error?<p className="mt-4 text-sm font-semibold text-red-700">{error}</p>:null}</div></main>}
