"use client";
import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/i18n";
type SupplyType = "talent" | "professional" | "production_partner";
const labels: Record<Locale, Record<SupplyType, string>> = { id: { talent: "Talent", professional: "Profesional", production_partner: "Production Partner" }, en: { talent: "Talent", professional: "Professional", production_partner: "Production Partner" } };
export function SupplyInterestForm({ locale }: { locale: Locale }) {
  const [email, setEmail] = useState(""); const [supplyType, setSupplyType] = useState<SupplyType>("talent"); const [consent, setConsent] = useState(false); const [website, setWebsite] = useState(""); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle"); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); setError(""); try { const response = await fetch("/api/public/supply-interest", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, supplyType, consent, website }) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? (locale === "id" ? "Pendaftaran belum dapat dikirim." : "Your submission could not be sent.")); setStatus("sent"); } catch (reason) { setStatus("error"); setError(reason instanceof Error ? reason.message : (locale === "id" ? "Pendaftaran belum dapat dikirim." : "Your submission could not be sent.")); } }
  if (status === "sent") return <div className="border border-[#e4957d]/55 bg-[#132923] p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e4957d]">Received</p><p className="mt-5 font-display text-4xl leading-none">{locale === "id" ? "Terima kasih." : "Thank you."}</p><p className="mt-5 max-w-md text-sm leading-6 text-white/70">{locale === "id" ? "Email Anda sudah masuk ke antrean kurasi. Kami menghubungi Anda saat ada pembukaan roster yang sesuai." : "Your email is in the curation queue. We will contact you when a fitting roster opening is available."}</p></div>;
  return <form onSubmit={submit} className="border border-white/15 bg-[#0b1513] p-6 shadow-2xl shadow-black/20 md:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e4957d]">{locale === "id" ? "Ajukan email" : "Submit your email"}</p><label className="mt-7 block text-sm font-semibold text-white/85">Email<input type="email" required autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="nama@email.com" className="mt-2 min-h-14 w-full border border-white/20 bg-white/5 px-4 text-base text-white outline-none placeholder:text-white/30 focus:border-[#e4957d]" /></label><fieldset className="mt-6"><legend className="text-sm font-semibold text-white/85">{locale === "id" ? "Saya mendaftar sebagai" : "I am applying as"}</legend><div className="mt-3 grid gap-2 sm:grid-cols-3">{(Object.keys(labels[locale]) as SupplyType[]).map((type) => <label key={type} className={`cursor-pointer border px-3 py-3 text-center text-xs font-bold uppercase tracking-[.08em] transition ${supplyType === type ? "border-[#e4957d] bg-[#e4957d] text-[#0b1513]" : "border-white/20 text-white/65 hover:border-white/50"}`}><input className="sr-only" type="radio" name="supplyType" value={type} checked={supplyType === type} onChange={() => setSupplyType(type)} />{labels[locale][type]}</label>)}</div></fieldset><label className="mt-6 flex cursor-pointer items-start gap-3 text-xs leading-5 text-white/55"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#e4957d]" required /><span>{locale === "id" ? "Saya setuju email ini digunakan Nusantara Star hanya untuk proses kurasi dan undangan onboarding." : "I agree that Nusantara Star may use this email only for curation and onboarding invitations."}</span></label><label className="sr-only" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={(event) => setWebsite(event.target.value)} /></label><button type="submit" disabled={status === "sending"} className="mt-7 min-h-14 w-full bg-white px-5 text-xs font-bold uppercase tracking-[.14em] text-[#0b1513] transition hover:bg-[#e4957d] disabled:cursor-wait disabled:opacity-60">{status === "sending" ? (locale === "id" ? "Mengirim…" : "Sending…") : (locale === "id" ? "Masuk antrean kurasi" : "Join curation queue")}</button>{status === "error" ? <p className="mt-4 text-sm text-[#f2a08a]">{error}</p> : null}</form>;
}
