"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

type Asset = { id: string; asset_type: string; original_filename: string | null; upload_status: string; review_status: string };
type Profile = {
  name: string; category: string; actType: string; baseCity: string; genres: string; musicStyles: string; vibeTags: string;
  capabilityTags: string; performanceFormats: string; eventTypes: string; bio: string; showDurationMinutes: string;
  managerName: string; managerEmail: string; managerWhatsapp: string; instagramUrl: string; tiktokUrl: string; youtubeUrl: string;
  baseRider: string; travelPolicy: string; accommodationPolicy: string;
};
type CategoryGroup = "music" | "host" | "speaker" | "specialty" | "unknown";

const blank: Profile = { name:"",category:"",actType:"",baseCity:"",genres:"",musicStyles:"",vibeTags:"",capabilityTags:"",performanceFormats:"",eventTypes:"",bio:"",showDurationMinutes:"",managerName:"",managerEmail:"",managerWhatsapp:"",instagramUrl:"",tiktokUrl:"",youtubeUrl:"",baseRider:"",travelPolicy:"",accommodationPolicy:"" };
const split=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);
const join=(v:unknown)=>Array.isArray(v)?v.join(", "):"";

const CATEGORIES=["Solo","Duo/Trio","Band","DJ","MC/Host","Speaker","Traditional/Ethnic","Specialty Performer"];
const COMMON_EVENT_TYPES=["Corporate","Wedding","Private Party","Hotel/Lounge","Festival","Brand Activation","Conference/MICE"];
const MUSIC={
  performanceFormats:["Full Band","Acoustic","Semi Acoustic","Playback","DJ Set","Hybrid"],
  musicStyles:["Top 40","Pop","Rock","Jazz","R&B/Soul","Dangdut","EDM","80s/90s","Indonesian Hits","International Hits","Ethnic/World"],
  vibeTags:["Chill","Elegant","Romantic","Upbeat","Party","High Energy"],
  capabilityTags:["Request Song","Bilingual Repertoire","Custom Setlist","MC Interaction","Singalong","Danceable"],
  genres:["Pop","Rock","Jazz","R&B/Soul","Dangdut","EDM","Alternative","Ethnic/World"],
};
const HOST={performanceFormats:["MC Solo","Co-Host","Moderator","Bilingual Host"],vibeTags:["Formal","Elegant","Warm","Energetic","Interactive"],capabilityTags:["Bilingual Hosting","Corporate Formal","Audience Interaction","Panel Moderation","Cue & Rundown Coordination"]};
const SPEAKER={performanceFormats:["Keynote","Panel","Workshop","Moderator"],vibeTags:["Formal","Inspirational","Interactive","Executive"],capabilityTags:["Bilingual Speaking","Q&A","Panel Discussion","Presentation Deck","Workshop Facilitation"]};
const SPECIALTY={performanceFormats:["Solo Act","Group Act","Stage Show","Roaming","Interactive"],vibeTags:["Elegant","Energetic","Family Friendly","Interactive","Spectacular"],capabilityTags:["Custom Performance","Audience Interaction","Special Equipment","Outdoor Performance","Indoor Performance"]};

function categoryGroup(category:string):CategoryGroup{
  const key=category.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
  if(["mc/host","mc host","mc","host","master of ceremony"].includes(key))return "host";
  if(["speaker","pembicara","keynote speaker"].includes(key))return "speaker";
  if(["specialty performer","special performer","performer","specialty"].includes(key))return "specialty";
  if(["solo","singer","soloist","vocalist","duo","trio","duo/trio","duo trio","band","dj","traditional","ethnic","traditional/ethnic","traditional ethnic"].includes(key))return "music";
  return "unknown";
}
function canonicalCategory(value:unknown){if(typeof value!=="string")return"";const raw=value.trim();const key=raw.toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");if(["singer","solo","soloist","vocalist"].includes(key))return"Solo";if(["duo","trio","duo/trio","duo trio"].includes(key))return"Duo/Trio";if(key==="band")return"Band";if(key==="dj")return"DJ";if(["mc","host","mc/host","mc host","master of ceremony"].includes(key))return"MC/Host";if(["speaker","pembicara","keynote speaker"].includes(key))return"Speaker";if(["specialty performer","special performer","performer","specialty"].includes(key))return"Specialty Performer";if(["traditional","ethnic","traditional/ethnic","traditional ethnic"].includes(key))return"Traditional/Ethnic";return raw}
const assetLabel=(t:string)=>({profile_photo:"Foto profil",press_photo:"Foto pers",live_performance:"Video live utama",showreel:"Showreel",event_clip:"Video event",rider_document:"Rider"}[t]??"File");
const statusLabel=(u:string,r:string)=>u!=="uploaded"?"Sedang diunggah":r==="approved"?"Disetujui":r==="rejected"?"Ditolak":"Terunggah · Menunggu tinjauan";
const onboardingStatus=(s:string)=>s==="not_started"?"Belum dimulai":s==="in_progress"?"Sedang dilengkapi":s==="submitted"?"Sudah dikirim":s==="approved"?"Disetujui":s.replaceAll("_"," ");

function resetCategorySpecific(p:Profile,category:string):Profile{return{...p,category,actType:"",genres:"",musicStyles:"",vibeTags:"",capabilityTags:"",performanceFormats:""}}

export function TalentOnboardingForm({talentId,token}:{talentId:string;token:string}){
 const[profile,setProfile]=useState<Profile>(blank);const[assets,setAssets]=useState<Asset[]>([]);const[status,setStatus]=useState("not_started");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[categoryOther,setCategoryOther]=useState(false);const[videoFile,setVideoFile]=useState<File|null>(null);
 const locked=status==="submitted"||status==="approved";const group=categoryGroup(profile.category);
 const formatOptions=group==="host"?HOST.performanceFormats:group==="speaker"?SPEAKER.performanceFormats:group==="specialty"?SPECIALTY.performanceFormats:group==="music"?MUSIC.performanceFormats:[];
 const vibeOptions=group==="host"?HOST.vibeTags:group==="speaker"?SPEAKER.vibeTags:group==="specialty"?SPECIALTY.vibeTags:group==="music"?MUSIC.vibeTags:[];
 const capabilityOptions=group==="host"?HOST.capabilityTags:group==="speaker"?SPEAKER.capabilityTags:group==="specialty"?SPECIALTY.capabilityTags:group==="music"?MUSIC.capabilityTags:[];
 const riderHint=group==="host"?"Untuk MC/host, fokus pada mic, monitor/cue, lectern/teleprompter, briefing/rundown, perjalanan, dan hospitality bila ada. Backline musik tidak wajib.":group==="speaker"?"Untuk speaker, fokus pada mic, lectern, layar/clicker, materi presentasi, perjalanan, akomodasi, dan kebutuhan pendamping bila ada.":group==="specialty"?"Untuk specialty performer, jelaskan kebutuhan alat, ruang/panggung, keselamatan, transport peralatan, dan kondisi khusus yang wajib.":group==="music"?"Untuk singer/band/DJ, rider dapat mencakup personel, audio, backline, soundcheck, transport/bagasi alat, hospitality, dan akomodasi.":"Untuk kategori lain, tulis hanya kebutuhan teknis dan operasional yang benar-benar berlaku. Sistem tidak akan menganggap talent ini sebagai talent musik.";
 async function refresh(){const r=await fetch(`/api/talent-onboarding/profile?talentId=${encodeURIComponent(talentId)}&token=${encodeURIComponent(token)}`,{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error("Gagal memuat onboarding");const s=d.submission??d.talent;const category=canonicalCategory(s?.category??"");setCategoryOther(Boolean(category&&!CATEGORIES.includes(category)));setStatus(d.talent?.onboarding_status??"not_started");setAssets(d.assets??[]);setProfile({name:s?.name??"",category,actType:s?.act_type??"",baseCity:s?.base_city??"",genres:join(s?.genres),musicStyles:join(s?.music_styles),vibeTags:join(s?.vibe_tags),capabilityTags:join(s?.capability_tags),performanceFormats:join(s?.performance_formats),eventTypes:join(s?.event_types),bio:s?.bio??"",showDurationMinutes:s?.show_duration_minutes?String(s.show_duration_minutes):"",managerName:s?.manager_name??"",managerEmail:s?.manager_email??"",managerWhatsapp:s?.manager_whatsapp??"",instagramUrl:s?.instagram_url??"",tiktokUrl:s?.tiktok_url??"",youtubeUrl:s?.youtube_url??"",baseRider:s?.base_rider??"",travelPolicy:s?.travel_policy??"",accommodationPolicy:s?.accommodation_policy??""})}
 useEffect(()=>{refresh().catch(()=>setError("Gagal memuat onboarding"))},[]);
 const field=(k:keyof Profile,l:string)=><label className="block text-sm font-semibold">{l}<input disabled={locked} value={profile[k]} onChange={e=>setProfile(x=>({...x,[k]:e.target.value}))} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></label>;
 const multi=(k:keyof Profile,l:string,options:readonly string[])=>{const selected=split(profile[k]);const extras=selected.filter(v=>!options.includes(v));const toggle=(value:string)=>setProfile(p=>{const cur=split(p[k]);return{...p,[k]:(cur.includes(value)?cur.filter(v=>v!==value):[...cur,value]).join(", ")}});return <fieldset className="block text-sm font-semibold"><legend>{l}</legend><div className="mt-2 flex flex-wrap gap-2">{options.map(o=><label key={o} className={`cursor-pointer border px-3 py-2 text-xs font-semibold ${selected.includes(o)?"border-black bg-black text-white":"border-black/15 bg-white"}`}><input disabled={locked} type="checkbox" checked={selected.includes(o)} onChange={()=>toggle(o)} className="sr-only"/>{o}</label>)}</div><input disabled={locked} value={extras.join(", ")} onChange={e=>setProfile(p=>({...p,[k]:[...selected.filter(v=>options.includes(v)),...split(e.target.value)].join(", ")}))} placeholder="Lainnya, pisahkan dengan koma" className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></fieldset>};
 async function save(){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/talent-onboarding/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,...profile,showDurationMinutes:profile.showDurationMinutes||null,genres:split(profile.genres),musicStyles:split(profile.musicStyles),vibeTags:split(profile.vibeTags),capabilityTags:split(profile.capabilityTags),performanceFormats:split(profile.performanceFormats),eventTypes:split(profile.eventTypes)})});if(!r.ok)throw new Error("Gagal menyimpan profil");setMessage("Profil tersimpan sebagai draft.");await refresh();return true}catch{setError("Gagal menyimpan profil");return false}finally{setBusy(false)}}
 async function uploadPhoto(file:File|null){if(!file)return;setBusy(true);setError("");try{const r=await fetch("/api/talent-onboarding/photo",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,fileName:file.name,mimeType:file.type,sizeBytes:file.size,assetType:"profile_photo"})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error();const c=getSupabaseBrowserClient();if(!c)throw new Error();const{error:ue}=await c.storage.from("talent-photos").uploadToSignedUrl(p.path,p.token,file,{contentType:file.type});if(ue)throw ue;const v=await fetch("/api/talent-onboarding/photo",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,assetId:p.assetId})});if(!v.ok)throw new Error();setMessage("Foto berhasil diunggah dan menunggu tinjauan.");await refresh()}catch{setError("Upload foto gagal")}finally{setBusy(false)}}
 async function uploadRider(file:File|null){if(!file)return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/talent-onboarding/rider",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,fileName:file.name,mimeType:file.type,sizeBytes:file.size})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error();const c=getSupabaseBrowserClient();if(!c)throw new Error();const{error:ue}=await c.storage.from("talent-documents").uploadToSignedUrl(p.path,p.token,file,{contentType:file.type});if(ue)throw ue;const v=await fetch("/api/talent-onboarding/rider",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,assetId:p.assetId})});if(!v.ok)throw new Error();setMessage("Rider tersimpan privat dan menunggu tinjauan.");await refresh()}catch{setError("Upload rider gagal")}finally{setBusy(false)}}
 async function uploadVideo(){if(!videoFile)return;setBusy(true);setError("");try{const r=await fetch("/api/talent-onboarding/video",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,fileName:videoFile.name,mimeType:videoFile.type,sizeBytes:videoFile.size,assetType:"live_performance"})});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error();const put=await fetch(p.uploadUrl,{method:"PUT",headers:{"content-type":videoFile.type},body:videoFile});if(!put.ok)throw new Error();const v=await fetch("/api/talent-onboarding/video",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,assetId:p.assetId})});if(!v.ok)throw new Error();setMessage("Video berhasil diunggah dan menunggu tinjauan.");setVideoFile(null);await refresh()}catch{setError("Upload video gagal")}finally{setBusy(false)}}
 async function submit(){setBusy(true);setError("");try{const saved=await save();if(!saved)return;setBusy(true);const r=await fetch("/api/talent-onboarding/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token})});if(!r.ok)throw new Error();setMessage("Onboarding berhasil dikirim untuk tinjauan.");await refresh()}catch{setError("Gagal mengirim onboarding")}finally{setBusy(false)}}
 function chooseCategory(value:string){if(value==="__other"){setCategoryOther(true);setProfile(p=>resetCategorySpecific(p,""));return}setCategoryOther(false);setProfile(p=>p.category===value?p:resetCategorySpecific(p,value))}
 const categorySelectValue=categoryOther?"__other":profile.category;const submitLabel=status==="approved"?"Sudah disetujui":status==="submitted"?"Sudah dikirim":busy?"Memproses…":"Kirim untuk Tinjauan";
 return <main className="min-h-screen bg-[#f5f3ee] px-5 py-10 text-[#171713] md:px-10"><div className="mx-auto max-w-3xl">
  <p className="eyebrow">Nusantara Star · Onboarding Talent</p><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><h1 className="text-4xl font-semibold tracking-[-0.03em]">Lengkapi profil talent</h1><span className="border border-black/10 bg-white px-3 py-2 text-xs font-semibold uppercase">{onboardingStatus(status)}</span></div>
  <p className="mt-3 text-sm text-black/55">Form menyesuaikan kategori talent. Isi hanya fakta yang benar; sistem tidak akan membuat kebutuhan yang tidak Anda berikan.</p>
  <section className="mt-8 grid gap-4 border border-black/10 bg-white p-5 md:grid-cols-2 md:p-6">
   {field("name","Nama talent")}
   <label className="block text-sm font-semibold">Kategori<select disabled={locked} value={categorySelectValue} onChange={e=>chooseCategory(e.target.value)} className="mt-2 w-full border border-black/15 bg-white px-3 py-3 font-normal disabled:bg-black/5"><option value="">Pilih</option>{CATEGORIES.map(x=><option key={x} value={x}>{x}</option>)}<option value="__other">Lainnya</option></select>{categoryOther?<input disabled={locked} value={profile.category} onChange={e=>setProfile(p=>({...p,category:e.target.value}))} placeholder="Tulis kategori lainnya" className="mt-2 w-full border border-black/15 px-3 py-3 font-normal"/>:null}</label>
   {group==="music"?<label className="block text-sm font-semibold">Jenis penampilan<select disabled={locked} value={profile.actType} onChange={e=>setProfile(p=>({...p,actType:e.target.value}))} className="mt-2 w-full border border-black/15 bg-white px-3 py-3 font-normal disabled:bg-black/5"><option value="">Pilih</option><option value="original_artist">Artis original</option><option value="cover_entertainment">Cover & entertainment</option></select></label>:null}
   {field("baseCity","Kota asal")}
   {formatOptions.length?multi("performanceFormats","Format tampil",formatOptions):null}
   {group==="music"?multi("musicStyles","Gaya musik",MUSIC.musicStyles):null}
   {vibeOptions.length?multi("vibeTags","Karakter / vibe",vibeOptions):null}{capabilityOptions.length?multi("capabilityTags","Kemampuan",capabilityOptions):null}
   {group==="music"?multi("genres","Genre",MUSIC.genres):null}{multi("eventTypes","Cocok untuk acara",COMMON_EVENT_TYPES)}{field("showDurationMinutes","Durasi tampil (menit)")}
   <label className="block text-sm font-semibold md:col-span-2">Bio<textarea disabled={locked} value={profile.bio} onChange={e=>setProfile(p=>({...p,bio:e.target.value}))} rows={5} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></label>
   {field("managerName","Manajer / PIC")}{field("managerWhatsapp","WhatsApp manajer/PIC")}{field("managerEmail","Email manajer/PIC")}
   <div className="md:col-span-2 border-t border-black/10 pt-5"><p className="text-sm font-semibold">Referensi media sosial · internal</p><p className="mt-1 text-xs text-black/50">Untuk verifikasi dan kurasi Nusantara Star. Tidak ditampilkan sebagai kontak klien.</p></div>
   {field("instagramUrl","Instagram")}{field("tiktokUrl","TikTok")}{field("youtubeUrl","YouTube")}
   <div className="md:col-span-2 border-t border-black/10 pt-5"><p className="text-sm font-semibold">Rider / kebutuhan operasional</p><p className="mt-1 text-xs leading-5 text-black/50">{riderHint}</p></div>
   <label className="block text-sm font-semibold md:col-span-2">Rider dasar<textarea disabled={locked} value={profile.baseRider} onChange={e=>setProfile(p=>({...p,baseRider:e.target.value}))} rows={5} placeholder={group==="host"?"Contoh: handheld wireless mic, cue monitor, rundown final H-1...":group==="speaker"?"Contoh: lavalier mic, lectern, confidence monitor, clicker...":group==="unknown"?"Tulis kebutuhan wajib yang benar-benar berlaku untuk kategori ini.":"Tulis kebutuhan wajib yang memang berlaku."} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></label>
   <label className="block text-sm font-semibold md:col-span-2">Dokumen rider <span className="font-normal text-black/45">(opsional)</span><input type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" disabled={busy||locked} onChange={e=>uploadRider(e.target.files?.[0]??null)} className="mt-3 block w-full text-sm font-normal"/><span className="mt-2 block text-xs font-normal text-black/45">PDF/DOCX/TXT maks. 15 MB · privat.</span></label>
   <label className="block text-sm font-semibold">Kebijakan perjalanan<textarea disabled={locked} value={profile.travelPolicy} onChange={e=>setProfile(p=>({...p,travelPolicy:e.target.value}))} rows={4} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></label>
   <label className="block text-sm font-semibold">Kebijakan akomodasi<textarea disabled={locked} value={profile.accommodationPolicy} onChange={e=>setProfile(p=>({...p,accommodationPolicy:e.target.value}))} rows={4} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal disabled:bg-black/5"/></label>
   <button disabled={busy||locked} onClick={save} className="w-fit border border-black px-4 py-2 text-sm font-semibold disabled:opacity-40">Simpan Draft</button>
  </section>
  <section className="mt-5 grid gap-4 md:grid-cols-2"><label className="border border-black/10 bg-white p-5 text-sm font-semibold">Foto profil<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||locked} onChange={e=>uploadPhoto(e.target.files?.[0]??null)} className="mt-3 block w-full text-sm font-normal"/></label><div className="border border-black/10 bg-white p-5 text-sm font-semibold">Video utama / showreel<input type="file" accept="video/mp4,video/webm" disabled={busy||locked} onChange={e=>setVideoFile(e.target.files?.[0]??null)} className="mt-3 block w-full text-sm font-normal"/>{videoFile?<button type="button" disabled={busy||locked} onClick={uploadVideo} className="mt-4 border border-black bg-black px-3 py-2 text-xs font-semibold text-white">Unggah Video</button>:null}<p className="mt-2 text-xs font-normal text-black/45">Gunakan video yang paling mewakili performa kategori ini.</p></div></section>
  <section className="mt-5 border border-black/10 bg-white p-5"><p className="text-sm font-semibold">Media & dokumen terunggah</p>{assets.length?assets.map(a=><div key={a.id} className="mt-2 flex flex-col gap-1 border-t border-black/10 pt-2 text-xs md:flex-row md:items-center md:justify-between"><span><strong>{assetLabel(a.asset_type)}</strong>{a.original_filename?` · ${a.original_filename}`:""}</span><span className="text-black/55">{statusLabel(a.upload_status,a.review_status)}</span></div>):<p className="mt-2 text-xs text-black/45">Belum ada media atau dokumen.</p>}</section>
  {message?<p className="mt-4 text-sm font-semibold text-green-700">{message}</p>:null}{error?<p className="mt-4 text-sm font-semibold text-red-700">{error}</p>:null}<button disabled={busy||locked} onClick={submit} className="mt-6 border border-black bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{submitLabel}</button>
 </div></main>
}
