"use client";

import { useEffect, useState } from "react";

type Question={key:string;question:string;required:boolean};
type Rider={version_no:number;source_filename?:string|null;missing_questions?:Question[];answers?:Record<string,string>;status:string};

export function TalentRiderCompletion({talentId,token}:{talentId:string;token:string}){
  const[rider,setRider]=useState<Rider|null>(null);const[answers,setAnswers]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[migrationRequired,setMigrationRequired]=useState(false);
  async function load(){const r=await fetch(`/api/talent-onboarding/rider-status?talentId=${encodeURIComponent(talentId)}&token=${encodeURIComponent(token)}`,{cache:"no-store"});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Gagal memuat status rider");setMigrationRequired(Boolean(d.migrationRequired));setRider(d.rider??null);setAnswers(d.rider?.answers??{})}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submit(){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/talent-onboarding/rider-status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({talentId,token,answers})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.detail??d?.error??"Gagal menyimpan jawaban rider");setRider(d.rider);setAnswers(d.rider?.answers??answers);setMessage(d.rider?.missing_questions?.length?"Jawaban tersimpan. Masih ada informasi dasar yang perlu dilengkapi.":"Informasi dasar rider sudah lengkap dan siap direview admin.")}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan jawaban rider")}finally{setBusy(false)}}
  if(migrationRequired||!rider)return null;
  const questions=rider.missing_questions??[];
  return <section className="bg-[#f5f3ee] px-5 pb-12 text-[#171713] md:px-10"><div className="mx-auto max-w-3xl border border-black/10 bg-white p-5 md:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">Kelengkapan Master Rider</p><p className="mt-1 text-xs text-black/50">Sistem hanya menanyakan informasi dasar yang belum ditemukan dari rider Anda.</p></div><span className="border border-black/10 px-2 py-1 text-xs font-semibold">v{rider.version_no}</span></div>{questions.length?<><div className="mt-5 space-y-4">{questions.map(q=><label key={q.key} className="block text-sm font-semibold">{q.question}<textarea value={answers[q.key]??""} onChange={e=>setAnswers(v=>({...v,[q.key]:e.target.value}))} rows={2} className="mt-2 w-full border border-black/15 px-3 py-3 font-normal" placeholder="Jawab singkat dan faktual"/></label>)}</div><button disabled={busy} onClick={submit} className="mt-4 border border-black bg-black px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Menyimpan…":"Simpan jawaban rider"}</button></>:<div className="mt-4 border border-green-700/20 bg-green-50 p-3 text-sm font-semibold text-green-800">✓ Informasi dasar rider sudah lengkap. Admin akan memeriksa source asli dan hasil normalisasi.</div>}{message?<p className="mt-3 text-sm font-semibold text-green-700">{message}</p>:null}{error?<p className="mt-3 text-sm font-semibold text-red-700">{error}</p>:null}</div></section>;
}
