import "server-only";
import { createClient } from "@supabase/supabase-js";
import { createR2PresignedUrl } from "@/lib/r2-presign";
import { youtubeEmbedUrlFromStorageKey, youtubePresentationFromStorageKey } from "@/lib/youtube";
import { parseInstagramMediaUrl, parseSoundCloudUrl } from "@/lib/profile-media";
import { getAvailabilityFreshness } from "@/lib/talent-engine/availability";
import type { AvailabilityFreshness, AvailabilityStatus } from "@/lib/talent-engine/types";

function getServerClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server environment is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export type PhotoSprite={col:number;row:number};
export type PublicTalentCard={id:string;name:string;category:string;base_city:string|null;service_cities?:string[];genres:string[];performance_formats?:string[];bio:string|null;photo_url:string|null;photo_sprite?:PhotoSprite|null;availability_status?:AvailabilityStatus|"unknown";availability_freshness?:AvailabilityFreshness;requires_live_confirmation?:boolean};
export type PublicTalentDetail=PublicTalentCard&{performance_formats:string[];event_types:string[];show_duration_minutes:number|null;videos:{id:string;provider:"cloudflare_r2"|"youtube_unlisted"|"soundcloud"|"instagram";title:string|null;description:string|null;url:string;source_url:string|null;asset_type:string;presentation:"landscape"|"portrait"|"audio"|"external"}[]};
function isOperationalName(name:string){return!name.toUpperCase().startsWith("SECURE-SMOKE-")}
function validDate(value:string|undefined){return Boolean(value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(new Date(`${value}T00:00:00Z`).getTime()))}
function publicAvailabilityStatus(value:unknown):AvailabilityStatus|"unknown"{return value==="available"||value==="tentative"||value==="booked"||value==="unavailable"?value:"unknown"}
export function publicCategoryId(category:string){const x=category.trim().toLowerCase();if(/(singer|penyanyi|vocalist|vokalis|solo)/.test(x))return"singer";if(/(band|group)/.test(x))return"band";if(/(mc|host|master of ceremony)/.test(x))return"mc";if(/\bdj\b|disc jockey/.test(x))return"dj";if(/(traditional|tradisional|cultural|budaya|ethnic|etnik)/.test(x))return"traditional";if(/(speaker|pembicara)/.test(x))return"speaker";if(/(special performer|specialty performer|specialty)/.test(x))return"specialty";return"other"}

const sprite="/demo-talents/sprite.webp";
const s=(col:number,row:number):PhotoSprite=>({col,row});
const demoBase:Array<Omit<PublicTalentDetail,"videos">>=[
{id:"demo-alya-prameswari",name:"Alya Prameswari",category:"Solo",base_city:"Jakarta",genres:["Pop","R&B/Soul"],bio:"Profil ilustrasi untuk demo Nusantara Star. Solo vocalist dengan karakter pop-soul untuk corporate event, wedding, dan private showcase.",photo_url:sprite,photo_sprite:s(0,0),performance_formats:["Full Band","Acoustic","Playback"],event_types:["Corporate","Wedding","Private Party"],show_duration_minutes:45},
{id:"demo-keisha-lazuardi",name:"Keisha Lazuardi",category:"Solo",base_city:"Bandung",genres:["Pop","Jazz"],bio:"Profil ilustrasi untuk demo Nusantara Star. Penyanyi dengan format fleksibel untuk intimate event hingga panggung corporate.",photo_url:sprite,photo_sprite:s(1,0),performance_formats:["Full Band","Acoustic"],event_types:["Corporate","Hotel/Lounge","Wedding"],show_duration_minutes:45},
{id:"demo-rafa-aditya",name:"Rafa Aditya",category:"Solo",base_city:"Surabaya",genres:["Pop","Indonesian Hits"],bio:"Profil ilustrasi untuk demo Nusantara Star. Solo singer untuk event brand, hospitality, dan private function.",photo_url:sprite,photo_sprite:s(2,0),performance_formats:["Acoustic","Full Band"],event_types:["Brand Activation","Hotel/Lounge","Private Party"],show_duration_minutes:45},
{id:"demo-nara-the-coast",name:"Nara & The Coast",category:"Band",base_city:"Jakarta",genres:["Indie Pop","Alternative"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band modern dengan format festival, corporate, dan brand activation.",photo_url:sprite,photo_sprite:s(3,0),performance_formats:["Full Band","Semi Acoustic"],event_types:["Festival","Corporate","Brand Activation"],show_duration_minutes:60},
{id:"demo-the-blue-hours",name:"The Blue Hours",category:"Band",base_city:"Bandung",genres:["Jazz","Pop"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band berkarakter elegant untuk gala dinner, lounge, dan wedding.",photo_url:sprite,photo_sprite:s(4,0),performance_formats:["Full Band","Acoustic"],event_types:["Wedding","Hotel/Lounge","Corporate"],show_duration_minutes:60},
{id:"demo-suara-kota",name:"Suara Kota",category:"Band",base_city:"Yogyakarta",genres:["Pop","Rock"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band energetic untuk kampus, festival, dan public event.",photo_url:sprite,photo_sprite:s(5,0),performance_formats:["Full Band"],event_types:["Festival","Brand Activation","Private Party"],show_duration_minutes:60},
{id:"demo-raka-mahendra",name:"Raka Mahendra",category:"MC/Host",base_city:"Jakarta",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. MC bilingual dengan pendekatan formal, hangat, dan audience-friendly.",photo_url:sprite,photo_sprite:s(0,1),performance_formats:["MC Solo","Bilingual Host","Moderator"],event_types:["Corporate","Conference/MICE","Brand Activation"],show_duration_minutes:null},
{id:"demo-nadine-surya",name:"Nadine Surya",category:"MC/Host",base_city:"Bali",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Host untuk destination event, hospitality, wedding, dan brand experience.",photo_url:sprite,photo_sprite:s(1,1),performance_formats:["MC Solo","Co-Host","Bilingual Host"],event_types:["Wedding","Hotel/Lounge","Brand Activation"],show_duration_minutes:null},
{id:"demo-arvin-pratama",name:"Arvin Pratama",category:"MC/Host",base_city:"Surabaya",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. MC corporate dan moderator untuk event formal maupun interactive session.",photo_url:sprite,photo_sprite:s(2,1),performance_formats:["MC Solo","Moderator"],event_types:["Corporate","Conference/MICE","Private Party"],show_duration_minutes:null},
{id:"demo-dimas-aruna",name:"Dimas Aruna",category:"DJ",base_city:"Bali",genres:["House","EDM"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ untuk nightlife, brand event, private party, dan resort activation.",photo_url:sprite,photo_sprite:s(3,1),performance_formats:["DJ Set"],event_types:["Private Party","Brand Activation","Hotel/Lounge"],show_duration_minutes:90},
{id:"demo-mira-nox",name:"Mira Nox",category:"DJ",base_city:"Jakarta",genres:["House","Pop Remix"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ dengan set modern untuk corporate after-party dan lifestyle event.",photo_url:sprite,photo_sprite:s(4,1),performance_formats:["DJ Set"],event_types:["Corporate","Brand Activation","Private Party"],show_duration_minutes:90},
{id:"demo-kayo",name:"KAYO",category:"DJ",base_city:"Bandung",genres:["EDM","Dance"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ energetic untuk festival mini, campus event, dan youth activation.",photo_url:sprite,photo_sprite:s(5,1),performance_formats:["DJ Set"],event_types:["Festival","Brand Activation","Private Party"],show_duration_minutes:90},
{id:"demo-svara-nusantara",name:"Svara Nusantara",category:"Traditional/Ethnic",base_city:"Yogyakarta",genres:["Ethnic/World","Contemporary"],bio:"Profil ilustrasi untuk demo Nusantara Star. Pertunjukan tradisi-kontemporer untuk cultural showcase, gala, dan institutional event.",photo_url:sprite,photo_sprite:s(0,2),performance_formats:["Group Act","Stage Show"],event_types:["Corporate","Festival","Conference/MICE"],show_duration_minutes:45},
{id:"demo-laras-bumi",name:"Laras Bumi",category:"Traditional/Ethnic",base_city:"Solo",genres:["Traditional","Ethnic/World"],bio:"Profil ilustrasi untuk demo Nusantara Star. Ensemble budaya untuk pembukaan acara, cultural night, dan special ceremony.",photo_url:sprite,photo_sprite:s(1,2),performance_formats:["Group Act","Stage Show"],event_types:["Corporate","Festival","Wedding"],show_duration_minutes:40},
{id:"demo-gema-pusaka",name:"Gema Pusaka",category:"Traditional/Ethnic",base_city:"Makassar",genres:["Traditional","Contemporary"],bio:"Profil ilustrasi untuk demo Nusantara Star. Cultural performance dengan kebutuhan teknis yang dikonfirmasi per acara.",photo_url:sprite,photo_sprite:s(2,2),performance_formats:["Group Act","Stage Show"],event_types:["Festival","Corporate","Private Party"],show_duration_minutes:40},
{id:"demo-maya-santoso",name:"Maya Santoso",category:"Speaker",base_city:"Surabaya",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Speaker untuk leadership, professional development, dan corporate session.",photo_url:sprite,photo_sprite:s(3,2),performance_formats:["Keynote","Panel","Workshop"],event_types:["Corporate","Conference/MICE"],show_duration_minutes:60},
{id:"demo-adrian-wibawa",name:"Adrian Wibawa",category:"Speaker",base_city:"Jakarta",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Business speaker dan panelist untuk conference, internal company event, dan executive forum.",photo_url:sprite,photo_sprite:s(4,2),performance_formats:["Keynote","Panel"],event_types:["Corporate","Conference/MICE"],show_duration_minutes:60},
{id:"demo-nadia-paramitha",name:"Nadia Paramitha",category:"Speaker",base_city:"Bandung",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Speaker dan workshop facilitator untuk creative, brand, dan professional audience.",photo_url:sprite,photo_sprite:s(5,2),performance_formats:["Keynote","Workshop","Panel"],event_types:["Corporate","Conference/MICE","Brand Activation"],show_duration_minutes:60}
];
const demoDetails:PublicTalentDetail[]=demoBase.map(t=>({...t,videos:[]}));
const demoById=new Map(demoDetails.map(t=>[t.id,t]));

async function photoUrl(supabase:ReturnType<typeof getServerClient>,talentId:string){const{data:asset}=await supabase.from("talent_assets").select("storage_key").eq("talent_id",talentId).eq("asset_type","profile_photo").eq("provider","supabase_storage").eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).order("sort_order",{ascending:true}).limit(1).maybeSingle();if(!asset)return null;const{data,error}=await supabase.storage.from("talent-photos").createSignedUrl(asset.storage_key,3600);return error?null:data.signedUrl}
function safeR2Url(storageKey:string){try{return createR2PresignedUrl("GET",storageKey,3600)}catch(error){console.error("Buyer-visible R2 media unavailable",error instanceof Error?error.message:String(error));return null}}
export async function loadPublicTalents(eventDate?:string):Promise<PublicTalentCard[]>{const supabase=getServerClient();const{data,error}=await supabase.from("talents").select("id,name,category,base_city,service_cities,genres,performance_formats,bio,last_calendar_updated_at").eq("supply_type","talent").eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").order("name",{ascending:true});if(error)throw new Error(error.message);const operational=(data??[]).filter(t=>isOperationalName(t.name));const selectedDate=validDate(eventDate)?eventDate!:null;const availabilityByTalent=new Map<string,AvailabilityStatus|"unknown">();if(selectedDate&&operational.length){const{data:rows,error:availabilityError}=await supabase.from("talent_availability").select("talent_id,status").in("talent_id",operational.map(t=>t.id)).eq("event_date",selectedDate);if(availabilityError)throw new Error(availabilityError.message);for(const row of rows??[])availabilityByTalent.set(row.talent_id,publicAvailabilityStatus(row.status))}const now=new Date();const real=await Promise.all(operational.map(async talent=>{const status=selectedDate?(availabilityByTalent.get(talent.id)??"unknown"):undefined;const freshness=selectedDate?getAvailabilityFreshness(talent.last_calendar_updated_at??"1970-01-01T00:00:00.000Z",now):undefined;return{id:talent.id,name:talent.name,category:talent.category,base_city:talent.base_city,service_cities:talent.service_cities??[],genres:talent.genres??[],performance_formats:talent.performance_formats??[],bio:talent.bio,photo_url:await photoUrl(supabase,talent.id),photo_sprite:null,availability_status:status,availability_freshness:freshness,requires_live_confirmation:selectedDate?!(status==="unavailable"||status==="booked"):undefined}}));return[...real.filter(t=>Boolean(t.photo_url)),...demoDetails]}
export async function loadPublicTalent(talentId:string):Promise<PublicTalentDetail|null>{const demo=demoById.get(talentId);if(demo)return demo;const supabase=getServerClient();const{data:talent,error}=await supabase.from("talents").select("id,name,category,base_city,genres,bio,performance_formats,event_types,show_duration_minutes").eq("id",talentId).eq("supply_type","talent").eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").maybeSingle();if(error)throw new Error(error.message);if(!talent||!isOperationalName(talent.name))return null;const profilePhoto=await photoUrl(supabase,talentId);if(!profilePhoto)return null;const{data:assets,error:assetsError}=await supabase.from("talent_assets").select("id,provider,storage_key,original_filename,title,description,asset_type").eq("talent_id",talentId).in("provider",["cloudflare_r2","youtube_unlisted","soundcloud","instagram"]).eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).in("asset_type",["live_performance","showreel","event_clip"]).order("sort_order",{ascending:true});if(assetsError)throw new Error(assetsError.message);const videos:PublicTalentDetail["videos"]=[];for(const asset of assets??[]){if(asset.provider==="youtube_unlisted"){const url=youtubeEmbedUrlFromStorageKey(asset.storage_key);if(url)videos.push({id:asset.id,provider:"youtube_unlisted",title:asset.title,description:asset.description,asset_type:asset.asset_type,url,source_url:asset.original_filename,presentation:youtubePresentationFromStorageKey(asset.storage_key)});continue}if(asset.provider==="soundcloud"){const media=parseSoundCloudUrl(asset.original_filename);if(media?.embedUrl)videos.push({id:asset.id,provider:"soundcloud",title:asset.title,description:asset.description,asset_type:asset.asset_type,url:media.embedUrl,source_url:media.canonicalUrl,presentation:"audio"});continue}if(asset.provider==="instagram"){const media=parseInstagramMediaUrl(asset.original_filename);if(media)videos.push({id:asset.id,provider:"instagram",title:asset.title,description:asset.description,asset_type:asset.asset_type,url:media.canonicalUrl,source_url:media.canonicalUrl,presentation:"external"});continue}const url=safeR2Url(asset.storage_key);if(url)videos.push({id:asset.id,provider:"cloudflare_r2",title:asset.title,description:asset.description,asset_type:asset.asset_type,url,source_url:null,presentation:"landscape"})}return{...talent,genres:talent.genres??[],performance_formats:talent.performance_formats??[],event_types:talent.event_types??[],photo_url:profilePhoto,photo_sprite:null,videos}}
