import "server-only";
import { createClient } from "@supabase/supabase-js";
import { createR2PresignedUrl } from "@/lib/r2-presign";

function getServerClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server environment is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export type PublicTalentCard={id:string;name:string;category:string;base_city:string|null;genres:string[];bio:string|null;photo_url:string|null};
export type PublicTalentDetail=PublicTalentCard&{performance_formats:string[];event_types:string[];show_duration_minutes:number|null;videos:{id:string;title:string|null;description:string|null;url:string;asset_type:string}[]};
function isOperationalName(name:string){return!name.toUpperCase().startsWith("SECURE-SMOKE-")}
export function publicCategoryId(category:string){const x=category.trim().toLowerCase();if(/(singer|penyanyi|vocalist|vokalis|solo)/.test(x))return"singer";if(/(band|group)/.test(x))return"band";if(/(mc|host|master of ceremony)/.test(x))return"mc";if(/\bdj\b|disc jockey/.test(x))return"dj";if(/(traditional|tradisional|cultural|budaya|ethnic|etnik)/.test(x))return"traditional";if(/(speaker|pembicara)/.test(x))return"speaker";if(/(special performer|specialty performer|specialty)/.test(x))return"specialty";return"other"}
async function photoUrl(supabase:ReturnType<typeof getServerClient>,talentId:string){const{data:asset}=await supabase.from("talent_assets").select("storage_key").eq("talent_id",talentId).eq("asset_type","profile_photo").eq("provider","supabase_storage").eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).order("sort_order",{ascending:true}).limit(1).maybeSingle();if(!asset)return null;const{data,error}=await supabase.storage.from("talent-photos").createSignedUrl(asset.storage_key,3600);return error?null:data.signedUrl}
export async function loadPublicTalents():Promise<PublicTalentCard[]>{const supabase=getServerClient();const{data,error}=await supabase.from("talents").select("id,name,category,base_city,genres,bio").eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").order("name",{ascending:true});if(error)throw new Error(error.message);const operational=(data??[]).filter(t=>isOperationalName(t.name));return Promise.all(operational.map(async talent=>({...talent,genres:talent.genres??[],photo_url:await photoUrl(supabase,talent.id)})))}
export async function loadPublicTalent(talentId:string):Promise<PublicTalentDetail|null>{const supabase=getServerClient();const{data:talent,error}=await supabase.from("talents").select("id,name,category,base_city,genres,bio,performance_formats,event_types,show_duration_minutes").eq("id",talentId).eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").maybeSingle();if(error)throw new Error(error.message);if(!talent||!isOperationalName(talent.name))return null;const{data:assets,error:assetsError}=await supabase.from("talent_assets").select("id,storage_key,title,description,asset_type").eq("talent_id",talentId).eq("provider","cloudflare_r2").eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).order("sort_order",{ascending:true});if(assetsError)throw new Error(assetsError.message);return{...talent,genres:talent.genres??[],performance_formats:talent.performance_formats??[],event_types:talent.event_types??[],photo_url:await photoUrl(supabase,talentId),videos:(assets??[]).map(asset=>({id:asset.id,title:asset.title,description:asset.description,asset_type:asset.asset_type,url:createR2PresignedUrl("GET",asset.storage_key,3600)}))}}
