import "server-only";
import { createClient } from "@supabase/supabase-js";
import { createR2PresignedUrl } from "@/lib/r2-presign";

function getServerClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server environment is not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export type PhotoSprite={col:number;row:number};
export type PublicTalentCard={id:string;name:string;category:string;base_city:string|null;genres:string[];bio:string|null;photo_url:string|null;photo_sprite?:PhotoSprite|null};
export type PublicTalentDetail=PublicTalentCard&{performance_formats:string[];event_types:string[];show_duration_minutes:number|null;videos:{id:string;title:string|null;description:string|null;url:string;asset_type:string}[]};
function isOperationalName(name:string){return!name.toUpperCase().startsWith("SECURE-SMOKE-")}
export function publicCategoryId(category:string){const x=category.trim().toLowerCase();if(/(singer|penyanyi|vocalist|vokalis|solo)/.test(x))return"singer";if(/(band|group)/.test(x))return"band";if(/(mc|host|master of ceremony)/.test(x))return"mc";if(/\bdj\b|disc jockey/.test(x))return"dj";if(/(traditional|tradisional|cultural|budaya|ethnic|etnik)/.test(x))return"traditional";if(/(speaker|pembicara)/.test(x))return"speaker";if(/(special performer|specialty performer|specialty)/.test(x))return"specialty";return"other"}

const sprite="/demo-talents/sprite.webp";
const s=(col:number,row:number):PhotoSprite=>({col,row});
const demoBase:Array<Omit<PublicTalentDetail,"videos">>=[
{id:"demo-alya-prameswari",name:"Alya Prameswari",category:"Solo",base_city:"Jakarta",genres:["Pop","R&B/Soul"],bio:"Profil ilustrasi untuk demo Nusantara Star. Solo vocalist dengan karakter pop-soul untuk corporate event, wedding, dan private showcase.",photo_url:sprite,photo_sprite:s(0,0),performance_formats:["Full Band","Acoustic","Playback"],event_types:["Corporate","Wedding","Private Party"],show_duration_minutes:45},
{id:"demo-keisha-lazuardi",name:"Keisha Lazuardi",category:"Solo",base_city:"Bandung",genres:["Pop","Jazz"],bio:"Profil ilustrasi untuk demo Nusantara Star. Penyanyi dengan format fleksibel untuk intimate event hingga panggung corporate.",photo_url:sprite,photo_sprite:s(1,0),performance_formats:["Full Band","Acoustic"],event_types:["Corporate","Hotel/Lounge","Wedding"],show_duration_minutes:45},
{id:"demo-rafa-aditya",name:"Rafa Aditya",category:"Solo",base_city:"Surabaya",genres:["Pop","Indonesian Hits"],bio:"Profil ilustrasi untuk demo Nusantara Star. Solo singer untuk event brand, hospitality, dan private function.",photo_url:sprite,photo_sprite:s(2,0),performance_formats:["Acoustic","Full Band"],event_types:["Brand Activation","Hotel/Lounge","Private Party"],show_duration_minutes:45},
{id:"demo-nara-the-coast",name:"Nara & The Coast",category:"Band",base_city:"Jakarta",genres:["Indie Pop","Alternative"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band modern dengan format festival, corporate, dan brand activation.",photo_url:sprite,photo_sprite:s(3,0),performance_formats:["Full Band","Semi Acoustic"],event_types:["Festival","Corporate","Brand Activation"],show_duration_minutes:60},
{id:"demo-the-blue-hours",name:"The Blue Hours",category:"Band",base_city:"Bandung",genres:["Jazz","Pop"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band berkarakter elegant untuk gala dinner, lounge, dan wedding.",photo_url:sprite,photo_sprite:s(4,0),performance_formats:["Full Band","Acoustic"],event_types:["Wedding","Hotel/Lounge","Corporate"],show_duration_minutes:60},
{id:"demo-suara-kota",name:"Suara Kota",category:"Band",base_city:"Yogyakarta",genres:["Pop","Rock"],bio:"Profil ilustrasi untuk demo Nusantara Star. Band energetic untuk kampus, festival, dan public event.",photo_url:sprite,photo_sprite:s(5,0),performance_formats:["Full Band"],event_types:["Festival","Brand Activation","Private Party"],show_duration_minutes:60},
{id:"demo-raka-mahendra",name:"Raka Mahendra",category:"MC/Host",base_city:"Jakarta",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. MC bilingual dengan pendekatan formal, hangat, dan audience-friendly.",photo_url:sprite,photo_sprite:s(0,1),performance_formats:["MC Solo","Bilingual Host","Moderator"],event_types:["Corporate","Conference/MICE","Brand Activation"],show_duration_minutes:null},
{id:"demo-nadine-surya",name:"Nadine Surya",category:"MC/Host",base_city:"Bali",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Host untuk destination event, hospitality, wedding, dan brand experience.",photo_url:sprite,photo_sprite:s(1,1),performance_formats:["MC Solo","Co-Host","Bilingual Host"],event_types:["Wedding","Hotel/Lounge","Brand Activation"],show_duration_minutes:null},
{id:"demo-arvin-pratama",name:"Arvin Pratama",category:"MC/Host",base_city:"Surabaya",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. MC corporate dan moderator untuk event formal maupun interactive session.",photo_url:sprite,photo_sprite:s(2,1),performance_formats:["MC Solo","Moderator"],event_types:["Corporate","Conference/MICE","Private Party"],show_duration_minutes:null},
{id:"demo-dimas-aruna",name:"Dimas Aruna",category:"DJ",base_city:"Bali",genres:["House","EDM"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ untuk nightlife, brand event, private party, dan resort activation.",photo_url:sprite,photo_sprite:s(3,1),performance_formats:["DJ Set"],event_types:["Private Party","Brand Activation","Hotel/Lounge"],show_duration_minutes:90},
{id:"demo-mira-nox",name:"Mira Nox",category:"DJ",base_city:"Jakarta",genres:["House","Pop Remix"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ dengan set modern untuk corporate after-party dan lifestyle event.",photo_url:sprite,photo_sprite:s(4,1),performance_formats:["DJ Set"],event_types:["Corporate","Brand Activation","Private Party"],show_duration_minutes:90},
{id:"demo-kayo",name:"KAYO",category:"DJ",base_city:"Bandung",genres:["EDM","Dance"],bio:"Profil ilustrasi untuk demo Nusantara Star. DJ energetic untuk festival mini, campus event, dan youth activation.",photo_url:sprite,photo_sprite:s(5,1),performance_formats:["DJ Set"],event_types:["Festival","Brand Activation","Private Party"],show_duration_minutes:90},
{id:"demo-svara-nusantara",name:"Svara Nusantara",category:"Traditional/Ethnic",base_city:"Yogyakarta",genres:["Ethnic/World","Contemporary"],bio:"Profil ilustrasi untuk demo Nusantara Star. Pertunjukan tradisi-kontemporer untuk cultural showcase, gala, dan institutional event.",photo_url:sprite,photo_sprite:s(0,2),performance_formats:["Group Act","Stage Show"],event_types:["Corporate","Festival","Conference/MICE"],show_duration_minutes:45},
{id:"demo-laras-bumi",name:"Laras Bumi",category:"Traditional/Ethnic",base_city:"Solo",genres:["Traditional","Ethnic/World"],bio:"Profil ilustrasi untuk demo Nusantara Star. Ensemble budaya untuk pembukaan acara, cultural night, dan special ceremony.",photo_url:sprite,photo_sprite:s(1,2),performance_formats:["Group Act","Stage Show"],event_types:["Corporate","Festival","Wedding"],show_duration_minutes:40},
{id:"demo-gema-pusaka",name:"Gema Pusaka",category:"Traditional/Ethnic",base_city:"Makassar",genres:["Traditional","Contemporary"],bio:"Profil ilustrasi untuk demo Nusantara Star. Cultural performance dengan kebutuhan teknis yang dikonfirmasi per acara.",photo_url:sprite,photo_sprite:s(2,2),performance_formats:["Group Act","Stage Show"],event_types:["Festival","Corporate","Private Party"],show_duration_minutes:40},
{id:"demo-maya-santoso",name:"Maya Santoso",category:"Speaker",base_city:"Surabaya",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Speaker untuk leadership, professional development, dan corporate session.",photo_url:sprite,photo_sprite:s(3,2),performance_formats:["Keynote","Panel","Workshop"],event_types:["Corporate","Conference/MICE"],show_duration_minutes:60},
{id:"demo-adrian-wibawa",name:"Adrian Wibawa",category:"Speaker",base_city:"Jakarta",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Business speaker dan panelist untuk conference, internal company event, dan executive forum.",photo_url:sprite,photo_sprite:s(4,2),performance_formats:["Keynote","Panel"],event_types:["Corporate","Conference/MICE"],show_duration_minutes:60},
{id:"demo-nadia-paramitha",name:"Nadia Paramitha",category:"Speaker",base_city:"Bandung",genres:[],bio:"Profil ilustrasi untuk demo Nusantara Star. Speaker dan workshop facilitator untuk creative, brand, dan professional audience.",photo_url:sprite,photo_sprite:s(5,2),performance_formats:["Keynote","Workshop","Panel"],event_types:["Corporate","Conference/MICE","Brand Activation"],show_duration_minutes:60}
];
const demoDetails:PublicTalentDetail[]=demoBase.map(t=>({...t,videos:[]}));
const demoById=new Map(demoDetails.map(t=>[t.id,t]));

async function photoUrl(supabase:ReturnType<typeof getServerClient>,talentId:string){const{data:asset}=await supabase.from("talent_assets").select("storage_key").eq("talent_id",talentId).eq("asset_type","profile_photo").eq("provider","supabase_storage").eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).order("sort_order",{ascending:true}).limit(1).maybeSingle();if(!asset)return null;const{data,error}=await supabase.storage.from("talent-photos").createSignedUrl(asset.storage_key,3600);return error?null:data.signedUrl}
export async function loadPublicTalents():Promise<PublicTalentCard[]>{const supabase=getServerClient();const{data,error}=await supabase.from("talents").select("id,name,category,base_city,genres,bio").eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").order("name",{ascending:true});if(error)throw new Error(error.message);const operational=(data??[]).filter(t=>isOperationalName(t.name));const real=await Promise.all(operational.map(async talent=>({...talent,genres:talent.genres??[],photo_url:await photoUrl(supabase,talent.id),photo_sprite:null})));return[...real.filter(t=>Boolean(t.photo_url)),...demoDetails]}
export async function loadPublicTalent(talentId:string):Promise<PublicTalentDetail|null>{const demo=demoById.get(talentId);if(demo)return demo;const supabase=getServerClient();const{data:talent,error}=await supabase.from("talents").select("id,name,category,base_city,genres,bio,performance_formats,event_types,show_duration_minutes").eq("id",talentId).eq("public_visible",true).eq("status","verified").eq("onboarding_status","approved").maybeSingle();if(error)throw new Error(error.message);if(!talent||!isOperationalName(talent.name))return null;const profilePhoto=await photoUrl(supabase,talentId);if(!profilePhoto)return null;const{data:assets,error:assetsError}=await supabase.from("talent_assets").select("id,storage_key,title,description,asset_type").eq("talent_id",talentId).eq("provider","cloudflare_r2").eq("upload_status","uploaded").eq("review_status","approved").eq("buyer_visible",true).order("sort_order",{ascending:true});if(assetsError)throw new Error(assetsError.message);return{...talent,genres:talent.genres??[],performance_formats:talent.performance_formats??[],event_types:talent.event_types??[],photo_url:profilePhoto,photo_sprite:null,videos:(assets??[]).map(asset=>({id:asset.id,title:asset.title,description:asset.description,asset_type:asset.asset_type,url:createR2PresignedUrl("GET",asset.storage_key,3600)}))}}
