import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Music2, Mic2, Radio, Sparkles, Users, Waves } from "lucide-react";
import { notFound } from "next/navigation";
import { categories } from "@/lib/data";
import { copy, isLocale } from "@/lib/i18n";
import { loadPublicTalents, publicCategoryId } from "@/lib/public-talents";
import { Reveal } from "@/components/reveal";

const icons = [Mic2, Music2, Radio, Sparkles, Waves, Users];

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const t = copy[locale];
  const publicTalents = await loadPublicTalents();
  const featuredTalents = publicTalents.slice(0, 3);
  const categoryCounts = new Map<string, number>();
  for (const talent of publicTalents) {
    const id = publicCategoryId(talent.category);
    categoryCounts.set(id, (categoryCounts.get(id) ?? 0) + 1);
  }

  return <>
    <section className="relative min-h-[calc(100svh-80px)] overflow-hidden bg-ink text-white"><Image src="/images/hero-indonesian-audience.png" alt={locale === "id" ? "Penonton Indonesia menikmati pertunjukan musik" : "Indonesian audience enjoying a live music performance"} fill priority className="object-cover opacity-70" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/30 to-transparent"/><div className="relative mx-auto flex min-h-[calc(100svh-80px)] max-w-[1440px] items-end px-5 pb-16 md:px-10 md:pb-24"><div className="max-w-4xl"><p className="eyebrow !text-[#e68b74]">{t.hero.eyebrow}</p><h1 className="mt-6 max-w-4xl font-display text-[clamp(3.4rem,8vw,7.5rem)] leading-[.9] tracking-[-.055em]">{t.hero.title}</h1><p className="mt-7 max-w-xl text-base leading-7 text-white/75 md:text-lg">{t.hero.body}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/talent`} className="inline-flex h-14 items-center justify-center gap-3 bg-white px-7 text-xs font-bold uppercase tracking-widest text-ink hover:bg-sand">{t.hero.cta}<ArrowRight size={17}/></Link><Link href={`/${locale}/brief`} className="inline-flex h-14 items-center justify-center border border-white/50 px-7 text-xs font-bold uppercase tracking-widest hover:bg-white hover:text-ink">{t.hero.secondary}</Link></div></div></div></section>

    <section className="px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1440px]"><Reveal><p className="eyebrow">{t.categories.eyebrow}</p><div className="mt-5 grid gap-6 md:grid-cols-2"><h2 className="max-w-3xl font-display text-4xl leading-tight md:text-6xl">{t.categories.title}</h2><p className="max-w-lg self-end text-base leading-7 text-black/60">{t.categories.body}</p></div></Reveal><div className="mt-16 grid grid-cols-1 border-t border-black/20 sm:grid-cols-2 lg:grid-cols-3">{categories.map((cat, i) => { const Icon = icons[i]; const count = categoryCounts.get(cat.id) ?? 0; return <Link href={`/${locale}/talent?category=${cat.id}`} key={cat.id} className="group flex items-center justify-between border-b border-black/20 px-1 py-7 sm:odd:border-r sm:odd:pr-7 sm:even:pl-7 lg:border-r lg:px-7 lg:first:pl-1 lg:nth-[3n]:border-r-0"><div className="flex items-center gap-5"><Icon strokeWidth={1.4}/><div><h3 className="font-display text-2xl">{locale === "id" ? cat.labelId : cat.labelEn}</h3><p className="mt-1 text-xs text-black/45">{count} talent</p></div></div><ArrowRight size={18} className="transition group-hover:translate-x-1"/></Link>})}</div></div></section>

    <section className="bg-white px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between"><div><p className="eyebrow">{t.featured.eyebrow}</p><h2 className="mt-4 font-display text-4xl md:text-6xl">{t.featured.title}</h2></div><Link href={`/${locale}/talent`} className="hidden items-center gap-2 border-b border-ink pb-2 text-xs font-bold uppercase tracking-widest md:flex">{t.featured.all}<ArrowRight size={15}/></Link></div>{featuredTalents.length ? <div className="mt-12 grid gap-10 md:grid-cols-3">{featuredTalents.map((talent, i) => <Reveal key={talent.id} delay={i * .08}><Link href={`/${locale}/talent/${talent.id}`} className="group block"><div className="aspect-[4/3] overflow-hidden bg-black/5">{talent.photo_url ? <img src={talent.photo_url} alt={locale === "id" ? `Foto profil ${talent.name}` : `${talent.name} profile photo`} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]" /> : <div className="flex h-full items-center justify-center text-xs font-semibold uppercase tracking-[0.12em] text-black/30">{locale === "id" ? "Foto menunggu kurasi" : "Photo pending curation"}</div>}</div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-black/40">{talent.category}{talent.base_city ? ` · ${talent.base_city}` : ""}</p><h3 className="mt-2 font-display text-3xl">{talent.name}</h3>{talent.genres.length ? <p className="mt-2 text-sm text-black/50">{talent.genres.slice(0, 3).join(" · ")}</p> : null}</Link></Reveal>)}</div> : <div className="mt-12 border border-black/10 bg-[#f8f7f3] p-8 text-sm text-black/55">{locale === "id" ? "Talent terkurasi akan tampil di sini setelah profil dan medianya disetujui." : "Curated talent will appear here after profile and media approval."}</div>}</div></section>

    <section id="process" className="px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1440px]"><p className="eyebrow">{t.process.eyebrow}</p><h2 className="mt-4 max-w-2xl font-display text-4xl md:text-6xl">{t.process.title}</h2><div className="mt-16 grid border-t border-black/20 md:grid-cols-3">{t.process.steps.map(([n,title,body]) => <div key={n} className="border-b border-black/20 py-8 md:border-r md:px-8 md:first:pl-0 md:last:border-r-0"><span className="font-display text-3xl text-ember">{n}</span><h3 className="mt-16 font-display text-3xl">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-black/55">{body}</p></div>)}</div></div></section>
    <section id="business" className="grid bg-moss text-white lg:grid-cols-2"><div className="relative min-h-[450px]"><Image src="https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85" alt={locale === "id" ? "Pertunjukan untuk acara perusahaan" : "Corporate event performance"} fill className="object-cover" sizes="(max-width:1024px) 100vw, 50vw"/></div><div className="flex items-center px-6 py-20 md:px-16 lg:px-20"><Reveal><p className="eyebrow !text-[#e68b74]">{t.business.eyebrow}</p><h2 className="mt-5 max-w-xl font-display text-5xl leading-[1.05] md:text-7xl">{t.business.title}</h2><p className="mt-7 max-w-xl leading-7 text-white/65">{t.business.body}</p><div className="mt-8 space-y-4">{t.business.points.map(p => <div key={p} className="flex items-center gap-3 text-sm"><Check size={17} className="text-[#e68b74]"/>{p}</div>)}</div><Link href={`/${locale}/brief`} className="mt-10 inline-flex h-14 items-center gap-3 bg-white px-7 text-xs font-bold uppercase tracking-widest text-ink">{t.nav.brief}<ArrowRight size={16}/></Link></Reveal></div></section>
    <section className="bg-ember px-5 py-24 text-white md:px-10 md:py-32"><Reveal className="mx-auto max-w-5xl text-center"><h2 className="font-display text-5xl leading-none md:text-8xl">{t.final.title}</h2><p className="mx-auto mt-7 max-w-xl text-white/70">{t.final.body}</p><Link href={`/${locale}/brief`} className="mt-10 inline-flex h-14 items-center gap-3 bg-white px-8 text-xs font-bold uppercase tracking-widest text-ink">{t.final.cta}<ArrowRight size={16}/></Link></Reveal></section>
  </>;
}
