import "server-only";

import { parseBriefText } from "./parse-brief";
import type { BriefFieldEvidence, BriefFieldName, StructuredBrief } from "./types";

const briefFields: BriefFieldName[] = ["eventType","eventDate","city","venue","audienceSize","talentCategory","genreStyle","budgetMin","budgetMax","performanceDurationMinutes","eventVibe","specialRequirements"];
const evidenceFieldSchema={type:"object",additionalProperties:false,properties:{status:{type:"string",enum:["explicit","normalized","inferred_review","missing"]},sourceExcerpt:{type:["string","null"]}},required:["status","sourceExcerpt"]};
const briefSchema={type:"object",additionalProperties:false,properties:{eventType:{type:["string","null"]},eventDate:{type:["string","null"],description:"YYYY-MM-DD when known"},city:{type:["string","null"]},venue:{type:["string","null"]},audienceSize:{type:["integer","null"]},talentCategory:{type:["string","null"]},genreStyle:{type:"array",items:{type:"string"}},budgetMin:{type:["integer","null"]},budgetMax:{type:["integer","null"]},performanceDurationMinutes:{type:["integer","null"]},eventVibe:{type:"array",items:{type:"string"}},specialRequirements:{type:"array",items:{type:"string"}},fieldEvidence:{type:"object",additionalProperties:false,properties:Object.fromEntries(briefFields.map(f=>[f,evidenceFieldSchema])),required:briefFields}},required:[...briefFields,"fieldEvidence"]};
function hasBriefValue(brief:StructuredBrief,field:BriefFieldName){const value=brief[field];return Array.isArray(value)?value.length>0:value!==null&&value!==undefined&&value!==""}
function normalizeEvidenceText(value:string){return value.toLowerCase().replace(/\s+/g," ").trim()}
function sanitizeEvidence(text:string,brief:StructuredBrief){const source=normalizeEvidenceText(text),incoming=brief.fieldEvidence??{},result:Partial<Record<BriefFieldName,BriefFieldEvidence>>={};for(const field of briefFields){if(!hasBriefValue(brief,field)){result[field]={status:"missing",sourceExcerpt:null};continue}const evidence=incoming[field],excerpt=typeof evidence?.sourceExcerpt==="string"?evidence.sourceExcerpt.trim():"",exists=excerpt.length>0&&source.includes(normalizeEvidenceText(excerpt));if(!exists){result[field]={status:"inferred_review",sourceExcerpt:null};continue}const status=evidence?.status;result[field]={status:status==="explicit"||status==="normalized"||status==="inferred_review"?status:"inferred_review",sourceExcerpt:excerpt}}return result}
function fallbackEvidence(brief:StructuredBrief){const result:Partial<Record<BriefFieldName,BriefFieldEvidence>>={};for(const field of briefFields)result[field]=hasBriefValue(brief,field)?{status:"inferred_review",sourceExcerpt:null}:{status:"missing",sourceExcerpt:null};return result}
function explicitCategoryNormalization(text:string,brief:StructuredBrief){const lower=text.toLowerCase();let category=brief.talentCategory;if(/\b(band cover|cover band)\b/.test(lower))category="Band";else if(!category&&/\bband\b/.test(lower))category="Band";else if(!category&&/\b(acoustic duo|akustik duo|duo akustik)\b/.test(lower))category="Acoustic";return {...brief,talentCategory:category,sourceText:text}}
export async function parseBriefWithAI(text:string):Promise<{brief:StructuredBrief;source:"ai"|"fallback"}>{const apiKey=process.env.GROQ_API_KEY;if(!apiKey){const raw=parseBriefText(text),brief=explicitCategoryNormalization(text,raw);return{brief:{...brief,fieldEvidence:fallbackEvidence(brief)},source:"fallback"}}try{const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.GROQ_MODEL??"openai/gpt-oss-20b",messages:[{role:"system",content:"Extract an entertainment event booking brief. Never invent missing facts. Return null or empty arrays when information is absent. Normalize Indonesian rupiah budgets to integer IDR and explicit dates to YYYY-MM-DD. Recognize explicit entertainment categories such as band, cover band, singer, DJ, MC, acoustic duo/trio, and traditional act. Keep explicit music/style phrases such as Top 40, Rock, Pop, Jazz, acoustic, full band, singalong, party, upbeat in genreStyle, eventVibe, or specialRequirements as appropriate. For every field return evidence. sourceExcerpt must be an exact excerpt copied from the user's text (maximum 80 characters), or null. Never fabricate an excerpt."},{role:"user",content:text}],response_format:{type:"json_schema",json_schema:{name:"nusantara_star_event_brief",strict:true,schema:briefSchema}},temperature:0}),cache:"no-store"});if(!response.ok)throw new Error(`Groq request failed: ${response.status}`);const payload=await response.json(),outputText=payload?.choices?.[0]?.message?.content;if(typeof outputText!=="string"||!outputText)throw new Error("No structured output returned");const parsed=JSON.parse(outputText) as StructuredBrief;const normalized=explicitCategoryNormalization(text,parsed);return{brief:{...normalized,fieldEvidence:sanitizeEvidence(text,normalized)},source:"ai"}}catch(error){console.error("Groq brief parsing failed, using deterministic fallback",error);const raw=parseBriefText(text),brief=explicitCategoryNormalization(text,raw);return{brief:{...brief,fieldEvidence:fallbackEvidence(brief)},source:"fallback"}}}
