import type { EngineTalent } from "./types";

const d = (date: string, status: "available" | "tentative" | "booked" | "unavailable") => ({ date, status });

export const demoTalents: EngineTalent[] = [
  {
    id: "demo-001",
    name: "Aruna Vale",
    category: "Penyanyi",
    genres: ["Pop", "Soul"],
    baseCity: "Jakarta",
    serviceCities: ["Jakarta", "Bandung", "Bogor", "Tangerang"],
    performanceFormats: ["Solo", "Acoustic", "Full Band"],
    eventTypes: ["Corporate", "Wedding", "Brand Activation"],
    audienceTags: ["Elegant", "Modern", "Pop", "Corporate"],
    budgetMin: 15000000,
    budgetMax: 28000000,
    reliabilityScore: 91,
    lastCalendarUpdatedAt: "2026-08-21T09:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "booked"), d("2026-09-25", "tentative")],
    isDemo: true,
  },
  {
    id: "demo-002",
    name: "Northline Society",
    category: "Band",
    genres: ["Pop", "Rock", "Top 40"],
    baseCity: "Jakarta",
    serviceCities: ["Jakarta", "Bandung", "Surabaya"],
    performanceFormats: ["Full Band"],
    eventTypes: ["Corporate", "Festival", "Brand Activation", "Private Event"],
    audienceTags: ["Energetic", "Young", "Upbeat", "Top 40"],
    budgetMin: 22000000,
    budgetMax: 38000000,
    reliabilityScore: 88,
    lastCalendarUpdatedAt: "2026-08-20T18:30:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available"), d("2026-09-25", "booked")],
    isDemo: true,
  },
  {
    id: "demo-003",
    name: "Maya Ratri",
    category: "MC",
    genres: ["Corporate", "Bilingual"],
    baseCity: "Jakarta",
    serviceCities: ["Jakarta", "Bali", "Bandung"],
    performanceFormats: ["MC", "Host"],
    eventTypes: ["Corporate", "Conference", "Wedding", "MICE"],
    audienceTags: ["Professional", "Elegant", "Bilingual", "Corporate"],
    budgetMin: 8000000,
    budgetMax: 18000000,
    reliabilityScore: 95,
    lastCalendarUpdatedAt: "2026-08-22T08:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "tentative"), d("2026-09-25", "available")],
    isDemo: true,
  },
  {
    id: "demo-004",
    name: "Svara Bumi",
    category: "Traditional",
    genres: ["Ethnic Contemporary", "Traditional"],
    baseCity: "Yogyakarta",
    serviceCities: ["Yogyakarta", "Jakarta", "Bali", "Surabaya"],
    performanceFormats: ["Ensemble", "Contemporary Traditional"],
    eventTypes: ["Corporate", "Cultural Event", "MICE", "Government"],
    audienceTags: ["Cultural", "Premium", "Indonesia", "Elegant"],
    budgetMin: 18000000,
    budgetMax: 35000000,
    reliabilityScore: 90,
    lastCalendarUpdatedAt: "2026-08-10T11:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available")],
    isDemo: true,
  },
  {
    id: "demo-005",
    name: "Luma Duo",
    category: "Acoustic",
    genres: ["Pop", "Jazz", "Acoustic"],
    baseCity: "Bandung",
    serviceCities: ["Bandung", "Jakarta", "Bogor"],
    performanceFormats: ["Duo", "Trio"],
    eventTypes: ["Corporate", "Wedding", "Hotel", "Private Event"],
    audienceTags: ["Warm", "Elegant", "Intimate", "Acoustic"],
    budgetMin: 6000000,
    budgetMax: 12000000,
    reliabilityScore: 87,
    lastCalendarUpdatedAt: "2026-08-19T14:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available"), d("2026-09-25", "available")],
    isDemo: true,
  },
  {
    id: "demo-006",
    name: "Kairo V",
    category: "DJ",
    genres: ["House", "Commercial", "Dance"],
    baseCity: "Bali",
    serviceCities: ["Bali", "Jakarta", "Surabaya"],
    performanceFormats: ["DJ Set"],
    eventTypes: ["Brand Activation", "Private Event", "Hotel", "Festival"],
    audienceTags: ["Energetic", "Nightlife", "Young", "Dance"],
    budgetMin: 12000000,
    budgetMax: 25000000,
    reliabilityScore: 84,
    lastCalendarUpdatedAt: "2026-07-30T10:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "tentative")],
    isDemo: true,
  },
  {
    id: "demo-007",
    name: "Elara June",
    category: "Penyanyi",
    genres: ["Jazz", "Pop", "R&B"],
    baseCity: "Surabaya",
    serviceCities: ["Surabaya", "Jakarta", "Bali"],
    performanceFormats: ["Solo", "Jazz Trio", "Full Band"],
    eventTypes: ["Corporate", "Wedding", "Hotel", "Private Event"],
    audienceTags: ["Elegant", "Sophisticated", "Jazz", "Premium"],
    budgetMin: 20000000,
    budgetMax: 42000000,
    reliabilityScore: 93,
    lastCalendarUpdatedAt: "2026-08-17T16:00:00+07:00",
    availability: [d("2026-09-12", "tentative"), d("2026-09-18", "available"), d("2026-09-25", "available")],
    isDemo: true,
  },
  {
    id: "demo-008",
    name: "Metro Bloom",
    category: "Band",
    genres: ["Jazz", "Soul", "Funk"],
    baseCity: "Bandung",
    serviceCities: ["Bandung", "Jakarta", "Bali"],
    performanceFormats: ["Quartet", "Full Band"],
    eventTypes: ["Corporate", "Wedding", "Hotel", "MICE"],
    audienceTags: ["Sophisticated", "Elegant", "Groovy", "Corporate"],
    budgetMin: 18000000,
    budgetMax: 32000000,
    reliabilityScore: 89,
    lastCalendarUpdatedAt: "2026-08-21T12:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available"), d("2026-09-25", "available")],
    isDemo: true,
  },
  {
    id: "demo-009",
    name: "Raka Pradana",
    category: "MC",
    genres: ["Corporate", "Entertainment"],
    baseCity: "Surabaya",
    serviceCities: ["Surabaya", "Jakarta", "Bali"],
    performanceFormats: ["MC", "Host"],
    eventTypes: ["Corporate", "Brand Activation", "Private Event"],
    audienceTags: ["Energetic", "Professional", "Corporate"],
    budgetMin: 7000000,
    budgetMax: 15000000,
    reliabilityScore: 86,
    lastCalendarUpdatedAt: "2026-08-16T09:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "booked"), d("2026-09-25", "available")],
    isDemo: true,
  },
  {
    id: "demo-010",
    name: "Asteria Strings",
    category: "Special Performer",
    genres: ["Classical", "Pop", "Instrumental"],
    baseCity: "Jakarta",
    serviceCities: ["Jakarta", "Bandung", "Bali"],
    performanceFormats: ["String Quartet", "String Trio"],
    eventTypes: ["Wedding", "Corporate", "Gala Dinner", "Private Event"],
    audienceTags: ["Elegant", "Luxury", "Formal", "Premium"],
    budgetMin: 10000000,
    budgetMax: 22000000,
    reliabilityScore: 94,
    lastCalendarUpdatedAt: "2026-08-22T07:30:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available"), d("2026-09-25", "tentative")],
    isDemo: true,
  },
  {
    id: "demo-011",
    name: "Nexa Rhythm",
    category: "Band",
    genres: ["Dangdut", "Pop", "Koplo"],
    baseCity: "Surabaya",
    serviceCities: ["Surabaya", "Malang", "Jakarta"],
    performanceFormats: ["Full Band"],
    eventTypes: ["Corporate", "Festival", "Community", "Private Event"],
    audienceTags: ["Festive", "Mass", "Energetic", "Dangdut"],
    budgetMin: 16000000,
    budgetMax: 30000000,
    reliabilityScore: 82,
    lastCalendarUpdatedAt: "2026-08-18T13:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available"), d("2026-09-25", "booked")],
    isDemo: true,
  },
  {
    id: "demo-012",
    name: "Bima Arsa",
    category: "Penyanyi",
    genres: ["Pop", "Rock"],
    baseCity: "Bandung",
    serviceCities: ["Bandung", "Jakarta", "Bogor"],
    performanceFormats: ["Solo", "Acoustic", "Full Band"],
    eventTypes: ["Corporate", "Brand Activation", "Private Event"],
    audienceTags: ["Energetic", "Young", "Pop Rock"],
    budgetMin: 12000000,
    budgetMax: 24000000,
    reliabilityScore: 79,
    lastCalendarUpdatedAt: "2026-08-05T15:00:00+07:00",
    availability: [d("2026-09-12", "available"), d("2026-09-18", "available")],
    isDemo: true,
  },
];
